### ISSUE TITLE
preauth or binauth for user login check

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#104]
PreAuth is for local FAS, or no FAS at all(use login.sh directly).

BinAuth also runs with and without FAS.

For a low-end local device(no FAS needed), if all I want is to give each user with their password to login then surf, which places should I do username-password check, is it better at PreAuth or BinAuth? I want to make this really simple(no TOS page, no second HTML page for "continue" button, etc. Just username/password then you login to use internet immediately).

**Comment by laoshaw** [comment]
I will keep using legacy that is the simplest I can find, a html with a binauth script, no FAS no PreAuth, please do not remove that feature in the future.

**Comment by bluewavenet** [comment]
@laoshaw 

> if all I want is to give each user with their password to login then surf, which places should I do username-password check, is it better at PreAuth or BinAuth?

**PreAuth**. This is because Binauth is a post-authentication processor, designed for local processing _after the call to openNDS for authentication_.
Yes it is true that in legacy mode you can process username/password in BinAuth but this has the unfortunate side effect that when client credentials fail for any reason, eg bad password, the client will potentially be left waiting for the client device CPD  to poll for connectivity with no error shown on the client device. This is made worse with some implementations of CPD as polling is disabled after connection and the only way forward is to disconnect and reconnect manually.

>  I want to make this really simple .... Just username/password..

You can achieve this very easily with some simple edits to login.sh
The v8.0.0 login.sh has been significantly refactored to make following the logic flow and therefore customisation quite simple. Let me know if you would like some help.

> please do not remove [legacy] in the future.

Legacy splash is deprecated and will be removed in the next major release. Support for legacy splash in v8.0.0 is provided to allow upgrades of openNDS, before migration of existing legacy splash implementations has been done.

As I mentioned earlier, I am quite happy to help. You will probably find much of your current BinAuth scripting can be utilised directly in a customised login.sh

**Comment by laoshaw** [comment]
Thanks. I will try to port binauth sitewide to login.sh (adding a value, say 3 for that option), it would be nice if it's part of login.sh by default.

**Comment by bluewavenet** [comment]
@laoshaw 

> adding a value, say 3 for that option

You got it, this is the intended use for the mode number of login_option_enabled :-D

You are very welcome to open a PR if you would like to add it to openNDS.
