### ISSUE TITLE
BinAuth not taking Session length argument

### ISSUE THREAD

**Issue by innoobijr** [openNDS/openNDS#107]
This is similar to #85. Currently running openNDS on a Raspberry Pi. It is used the ndsctl directly via command line with the session length, quotes, etc, it properly configures the settings for an authenticated user. However, when using the binauth script it is not parsing/evaluating the session length.

**Comment by innoobijr** [comment]
There is a bug in the http_microhttpd.c file. I've fixed it and will include the PR for the fix soon.

**Comment by bluewavenet** [comment]
@innoobijr 
Thankyou for opening the issue.
Could you share your configuration file? I don't seem to be able to replicate the issue here, I am perhaps not understanding how you are using binauth.

**Note**: If the authentication method is ndsctl_auth, then binauth does not set quotas, it just logs the quota values that were set by ndsctl .

**Comment by bluewavenet** [comment]
@innoobijr 
As I cannot replicate this issue and you have not given any additional information I am closing this.

If you can shed any light on your problem please feel free to reopen.
