### ISSUE TITLE
openNDS seems to crash on every client connect

### ISSUE THREAD

**Issue by iTommix** [openNDS/openNDS#118]
OpenWrt: 19.07.7 r11306-c4a6851c72
openNDS: 5.2.0 (installed by opk)
MHD: v0.9.69 (warnings in log)

I can connect to my FAS www.example.com, and the wifi indicator on my smartphone become LTE (not wifi). After given the credentials my smartphone says "server not reachable", and i see in logread openNDS seems to be crashed because this appears:

Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: openNDS Version 5.2.0
Fri Feb 19 14:24:43 2021 daemon.err opennds[5367]: libmicrohttpd is out of date, please upgrade to v0.9.69 or v0.9.70
Fri Feb 19 14:24:43 2021 daemon.err opennds[5367]: Client entered data may be translated incorrectly, use with this possibility in mind...
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Attempting to Bind to interface: br-lan
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Interface br-lan is up
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Interface br-lan is at 192.168.1.1 (d8:cb:8a:cd:de:f2)
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Created web server on 192.168.1.1:2050
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Handle [134621232]
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: SSL Provider is active
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: FAS URL is http://example.com:80/wifi/login.php
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Forwarding Authentication is Enabled.
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Binauth is Enabled.
Fri Feb 19 14:24:43 2021 daemon.notice opennds[5367]: Initializing firewall rules

Also this is noticed in logs:

`Fri Feb 19 14:19:21 2021 daemon.info procd: Instance opennds::cfg01995c s in a crash loop 6 crashes, 0 seconds since last crash`

Same configuration (i can post here) works before on nodogsplash.

**ndsctl status:**

Version: 5.2.0
Uptime: 11m 14s
Gateway Name: OpenWrt openNDS
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://192.168.1.1:2050
Binauth Script: /root/iptables.sh
Preauth: Disabled
FAS: Secure Level 2, URL: http://example.com:80/wifi/login.php
Client Check Interval: 60s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Traffic control: no
Total download: 2 kByte; avg: 0.03 kbit/s
Total upload: 48 kByte; avg: 0.58 kbit/s

Client authentications since start: 0
Current clients: 0

Blocked MAC addresses: none
Allowed MAC addresses: N/A
Trusted MAC addresses: none

**uci show opennds:**

opennds.@opennds[0]=opennds
opennds.@opennds[0].enabled='1'
opennds.@opennds[0].debuglevel='0'
opennds.@opennds[0].fwhook_enabled='1'
opennds.@opennds[0].login_option_enabled='0'
opennds.@opennds[0].use_outdated_mhd='1'
opennds.@opennds[0].unescape_callback_enabled='0'
opennds.@opennds[0].gatewayinterface='br-lan'
opennds.@opennds[0].gatewayport='2050'
opennds.@opennds[0].gatewayname='OpenWrt openNDS'
opennds.@opennds[0].maxclients='250'
opennds.@opennds[0].preauthidletimeout='30'
opennds.@opennds[0].authidletimeout='120'
opennds.@opennds[0].sessiontimeout='1200'
opennds.@opennds[0].checkinterval='60'
opennds.@opennds[0].uploadrate='0'
opennds.@opennds[0].downloadrate='0'
opennds.@opennds[0].ratecheckwindow='2'
opennds.@opennds[0].uploadquota='0'
opennds.@opennds[0].downloadquota='0'
opennds.@opennds[0].binauth='/root/iptables.sh'
opennds.@opennds[0].fasport='80'
opennds.@opennds[0].fasremotefqdn='example.com'
opennds.@opennds[0].fasremoteip='m.y.i.p'
opennds.@opennds[0].faspath='/wifi/login.php'
opennds.@opennds[0].faskey='1234567890'
opennds.@opennds[0].fas_secure_enabled='2'
opennds.@opennds[0].authenticated_users='allow all'
opennds.@opennds[0].users_to_router='allow tcp port 53' 'allow udp port 53' 'allow udp port 67' 'allow tcp port 22' 'allow tcp port 23' 'allow tcp port 80' 'allow tcp port 443'

**Comment by bluewavenet** [comment]
@iTommix 
The crash you see in the logs was some 5 minutes earlier. **Were you trying to start without  use_outdated_mhd set to 1?**
openNDS will fail to start if not set or set to 0. Procd will interpret this as a "crash" and try to restart openNDS numerous times before giving up.

**If you want to run fas_secure_enabled 2 or 3 you must also have packages php7-cli and php7-mod-openssl installed,** otherwise it will also fail to start as above.

I would try with the openNDS default config before trying to migrate an old NoDogSplash config.

`opennds.@openNDS[0].binauth='/root/iptables.sh'`

What is this? An odd name for a BinAuth script. Also there is no guarantee an old NoDogsplash BinAuth script will be compatible with openNDS - might be - it depends on what you have in it.

**Can you also state what hardware you are running openNDS on.**

I would suggest also that you upgrade to the latest openNDS and libmicrohttpd from OpenWrt Snapshots. These are in fact stable packages, despite being in Snapshots.
Download both to /tmp then install libmicrohttpd first, followed by openNDS.

**Comment by iTommix** [comment]
> Were you trying to start without use_outdated_mhd set to 1?

No, this opption is set to 1

`option use_outdated_mhd '1'`

> If you want to run fas_secure_enabled 2 or 3 you must also have packages php7-cli and php7-mod-openssl installed, otherwise it will also fail to start as above.

Of course, i have.

> What is this? An odd name for a BinAuth script. Also there is no guarantee an old NoDogsplash BinAuth script will be compatible with openNDS - might be - it depends on what you have in it.

There is nothing in there, except make a rule for iptabes:

`#!/bin/sh

METHOD="$1"
MAC="$2"

case "$METHOD" in
  auth_client)
    #iptables -I zone_lan_forward 2 -m mac --mac-source "$MAC" -d 192.168.178.0/24 -m comment --comment "!fw3: GUEST" -j zone_wan_dest_REJECT
    printf "iptables -I zone_lan_forward 2 -m mac --mac-source $MAC -d 192.168.178.0/24 -m comment --comment '!fw3: GUEST' -j zone_wan_dest_REJECT\n" >> /etc/firewall.user
    /etc/init.d/firewall restart
    echo 86400 0 0
    exit 0
    ;;
  client_auth|client_deauth|idle_deauth|timeout_deauth|ndsctl_auth|ndsctl_deauth|shutdown_deauth)
    INGOING_BYTES="$3"
    OUTGOING_BYTES="$4"
    SESSION_START="$5"
    SESSION_END="$6"
    # client_auth: Client authenticated via this script.
    # client_deauth: Client deauthenticated by the client via splash page.
    # idle_deauth: Client was deauthenticated because of inactivity.
    # timeout_deauth: Client was deauthenticated because the session timed out.
    # ndsctl_auth: Client was authenticated by the ndsctl tool.
    # ndsctl_deauth: Client was deauthenticated by the ndsctl tool.
    # shutdown_deauth: Client was deauthenticated by Nodogsplash terminating.
    ;;
esac`

> Can you also state what hardware you are running openNDS on.

It's x86, not a router.

**Comment by iTommix** [comment]
@bluewavenet 

I followed your suggestion to install the packages from snapshot. I download them to /tmp/ but i was not able to install them on the command line. opkg always downloaded the packages from stable.

So i added the sources urls from snapshot in LuCI to the package manager and installed from there. While LuCI show me i have the right version installed
![Bildschirmfoto 2021-02-20 um 11 36 23](https://user-images.githubusercontent.com/22579516/108592885-82a03180-7370-11eb-9815-4ac5ef98a4e1.png)

ndsctl status gives me:

**Version: 5.2.0**
Uptime: 4m 29s
Gateway Name: OpenWrt openNDS
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
...

Can you guide me to install the snapshot builds without upgrade the whole system to snapshot?

Thank you in advance

**Comment by bluewavenet** [comment]
@iTommix 

> Can you guide me ...

Before doing anything else, make a backup of your customised /etc/config/opennds
**Then, _very important_, delete /etc/config/opennds**

Assuming x86-64, download:
https://downloads.openwrt.org/snapshots/packages/x86_64/routing/opennds_8.0.0-1_x86_64.ipk
and
https://downloads.openwrt.org/snapshots/packages/x86_64/packages/libmicrohttpd-no-ssl_0.9.71-1_x86_64.ipk

Copy both to /tmp on your "router" configured x86.

Then run:
`opkg install /tmp/libmicrohttpd-no-ssl_0.9.71-1_x86_64.ipk --force-reinstall`
and
`opkg install /tmp/opennds_8.0.0-1_x86_64.ipk --force-reinstall`

Now add the following line to the newly installed /etc/config/opennds:
`option gatewayfqdn 'status.client'`

Now restart:
`service opennds restart`

Finally check by running:
`ndsctl status`

and

`logread | grep opennds`

Test now with a client and you should get the default "click to continue" splash page sequence.
It is important do all these steps in this order to test all is well, before moving on to your desired configuration.

**Comment by bluewavenet** [comment]
@iTommix 
It is not clear to me what you are trying to do with your binauth script.
Perhaps you could explain, as I suspect the functionality is built in to openNDS already......

**Comment by iTommix** [comment]
> @iTommix
> It is not clear to me what you are trying to do with your binauth script.
> Perhaps you could explain, as I suspect the functionality is built in to openNDS already......

@bluewavenet  

First of all thanks for the guide. I will try it.

**binauth:**

My employees and guests should stay on the same wifi, but guests should not be able to access the intranet, thats why i block them by iptables after successfull login.

Thats all.

I dont think openNDS can do that for me ;)

**Comment by bluewavenet** [comment]
@iTommix 
Note for your information, openNDS v8.1.0 is now released and should appear in OpenWrt snapshots in a day or two..
It is ok to continue with 8.0.0 for now and upgrade when available.

**Comment by bluewavenet** [comment]
@iTommix 

You have in your binauth script:
```
printf "iptables -I zone_lan_forward 2 -m mac --mac-source $MAC -d 192.168.178.0/24 -m comment --comment '!fw3: GUEST' -j zone_wan_dest_REJECT\n" >> /etc/firewall.user
/etc/init.d/firewall restart
```

**_Restarting the firewall will also restart openNDS, so this is what is causing your apparent "crash"_**

> My employees and guests should stay on the same wifi, but guests should not be able to access the intranet....

Do you have a "Guest" ssid and a "Staff" ssid? Otherwise how do you differentiate between the two types of users?

**Comment by iTommix** [comment]
@bluewavenet 

> Restarting the firewall will also restart openNDS, so this is what is causing your apparent "crash"

I dont think so, otherwise the rule must be in the iptables if the script is executed

>Do you have a "Guest" ssid and a "Staff" ssid?

No. It's only one SSID

>how do you differentiate between the two types of users?

It's easy:

Only guests have to authenticate by FAS, emplyees are trusted in openNDS via ndsctl and dont need to authenticate. So, the script will be executed for guests only.

**Comment by bluewavenet** [comment]
@iTommix 
fw3 and openNDS must work together, otherwise fw3 would clear openNDS's firewall settings.
This resetting is essential and is specifically coded. Restarting fw3 **WILL** restart openNDS.

**Comment by iTommix** [comment]
> @iTommix
> fw3 and openNDS must work together, otherwise fw3 would clear openNDS's firewall settings.
> This resetting is essential and is specifically coded. Restarting fw3 **WILL** restart openNDS.

I know... but it should not be a problem openNDS will restarted **AFTER** a guest has authenticated, right?

**Comment by bluewavenet** [comment]
@iTommix 
Every time a guest authenticates, your binauth script restarts firewall. Firewall informs openNDS, so openNDS restarts also, thus deauthenticating everyone.

**Comment by iTommix** [comment]
@bluewavenet 

>thus deauthenticating everyone.

Thats bad. Maybe better use an reload instead of restart.

If i inject rules in iptables directly, they dont have an effect. I dont know why...

**Comment by bluewavenet** [comment]
@iTommix 
What you need is:
`list authenticated_users 'block to 192.168.178.0/24'`

Trusted users will still be allowed access to each other.

**_However_**, this is a functionality that must not have been tried by anyone for a very long time because on testing it here now I find there is a bug that prevents it from working!

It looks a simple fix, so it also looks like there is going to be release 8.1.1 this weekend :-D

**Comment by iTommix** [comment]
@bluewavenet 

`list authenticated_users 'block to 192.168.178.0/24'`

Sounds great, but i can't do this on the fly, yes? It must be done in the config?

**Comment by bluewavenet** [comment]
@iTommix 

> If i inject rules in iptables directly, they dont have an effect.

This is because the iptables rules are in a chain. Once a match is found the chain normally exits.
openNDS iptables rules are always first in the chain.

> This affect only AUTHENTICATED clients, not TRUSTED, right?

Correct... as long as I fix it properly ;-)

**Comment by iTommix** [comment]
@bluewavenet 

>as long as I fix it properly ;-)

I will wait then till you fixed it. Give me please a sign if so :)

Thanks...

**Comment by bluewavenet** [comment]
@iTommix 

> No. It's only one SSID

And by implication a single ip network. **My apologies for not reading your replies completely**.

On a single ip network, as far as I know, this cannot reliably be done, and nothing to do with the bug I found.
(The bug is to do with trusted clients)
Your iptables rule, if it could be added, would also prevent access to the ip gateway address, thus blocking Internet access. In addition, if you extended the wireless network with additional access points, the rule would not provide any isolation unless all traffic was bridged through the router lan interface, and this would not be the case with external APs or switches.
What you need is an open guest network that openNDS is managing and a separate closed staff network.
This can be done quite easily on a single router if that is what you have. It would be a matter of configuration changes.

**Comment by iTommix** [comment]
@bluewavenet 

Sorry for my late reply.

From my opnion with iptables and mac-filter it should work. Of course, restart iptable and therefore openNDS is not a good idea. But normally injected rules on the fly should work in iptables without restart.

>(The bug is to do with trusted clients)

What kind of bug is it? I didnt noticed it.

**Comment by bluewavenet** [comment]
@iTommix 

> What kind of bug is it? 

It turned out it was to do with a startup failure if certain firewall settings were added to the config. See PR #119 

> From my opinion with iptables and mac-filter it should work

Theoretically yes, but only for traffic passing through the interface in question (ie the default ip gateway). There is no guarantee that all traffic on a subnet will go through the default gateway address. Also you are blocking the entire subnet, including the gateway address, so if this did work, the client would be subsequently blocked from everything including accessing the Internet through the gateway.

> normally injected rules on the fly should work in iptables without restart.

Yes, this is true, but you are not injecting rules, you are adding them to the firewall config so they will be "injected" later, on a restart or at the boot-time startup of the firewall.

> Of course, restart iptable and therefore openNDS is not a good idea

The OpenWRT firewall (fw3) is **NOT** the same thing as iptables.
Both fw3 and openNDS **use** iptables to set up their own rules.
Iptables is the API interface provided to add "tables" to the kernel. Iptables is not a service.

**Comment by iTommix** [comment]
@bluewavenet 

>Yes, this is true, but you are not injecting rules, you are adding them to the firewall config so they will be "injected" later, on a restart or at the boot-time startup of the firewall.

You have seen how i do it now. At first i did inject my rules on the fly, instead hold them in a config (printf). But maybe on a wrong position. I have to check it again.

>Theoretically yes, but only for traffic passing through the interface in question (ie the default ip gateway).

Thats true, and i thought about. I dont know why, but it worked, even it shouldnt.

Of course, we have access points they can handle multiple SSID's. I just have to work out to handle this by openWRT. What i dont want is WPA2 (or similar) for employees. Maybe Radius.

**Comment by bluewavenet** [comment]
@iTommix 

> I dont know why, but it worked

If a client is connected to the wireless interface of the openNDS router (without openNDS running) then it might work for individual ip addresses, as that interface will pass traffic to the lan bridge interface internally via the gateway address.

If you have multiple access points around the site, then no, it will not work unless trying to connect via the default gateway.
It would be a very "hit and miss" situation depending on your lan setup eg ethernet switches, multiple access points etc.

openNDS can identify which interface a client is using and if an 802.11s mesh is used, which mesh node the client is connected to. It will all come down to the details of the network architecture you have.
Can you share a diagram?
It might be better to close this issue, and open a new one to discuss this new problem as it is no longer "openNDS seems to crash on every client connect". I think that is resolved as it was caused by the firewall restart.

**Comment by iTommix** [comment]
@bluewavenet 

>It might be better to close this issue, and open a new one to discuss this new problem as it is no longer "openNDS seems to crash on every client connect". I think that is resolved as it was caused by the firewall restart.

Agree. Thank you anyway for discuss this topic with me. Will see which way i'll go.
