### ISSUE TITLE
Setting up Text Message PINs

### ISSUE THREAD

**Issue by meta-space** [openNDS/openNDS#126]
I'm trying to setup a super simple captive portal. But I have a conceptual question.

I want to setup a system where guests are issued four-digit PINs to their phones. The PINs are then used as authentication code on the login page. So, I think I need a two-step authentication process:

0. Guest is redirected to login page
1. The guest is asked for their phone number.
    --> phone number is submitted to server; PIN is generated
    --> PIN is sent to that number
2. They enter the PIN number they received
    --> if it matches they are authenticated

After reading the documentation I think PreAuth could probably achieve this - either by modifying the existing username&email login or writing a custom one(?). The key point is that I have to be able to perform multiple steps/form submits without interrupting the authentication process.

I'm not familiar with openNDS and I'm uncertain what the simplest way to implement such a solution would be.
PreAuth seems the way to go. FAS seems like overkill for this as I don't have a user DB or anything setup... 🤔

**Comment by bluewavenet** [comment]
@meta-space 
This is quite straightforward.

But first bare in mind that PreAuth is nothing more than an implementation of FAS that uses openNDS's built in web server, thus enabling a self contained system. Whether you use PreAuth (local) or a full independent-of-openNDS FAS hosted anywhere, depends on the detail of what you want to achieve.

You say:
> phone number is submitted to server 

The question to ask yourself is what and where is this key-generating/sms-sending server? There are many answers to this question depending on the detail of your project.

If you could give a brief outline of the specific requirement, I could go into more detail.

There is something else to consider - As the trend is towards larger and larger data quotas in mobile data plans at lowering cost, perhaps your potential users would just continue using their mobile data rather than use a system such as this? This is certainly the trend in many areas. I'm not necessarily saying this is not currently worthwhile doing in your situation, but things are changing rapidly in the mobile data world.

An alternative is to use email rather than sms. This can have many advantages, particularly at venues that do not have a good mobile signal, or only covered by some mobile networks - as can often happen in rural areas.

**Comment by meta-space** [comment]
@bluewavenet Hi Rob,

This is a little project for a term paper. Nothing that needs to be production-ready 😀

We have setup openWRT + openNDS on a raspberry pi, which acts as an access point. It is also hooked up to an GSM/LTE modem to send the text messages. Everything is done on the pi, there are no other external services involved.

I thought upon generation of the PIN, I'd store the phonenumber and its PIN somewhere (perhaps a single file). 
Later, during verification I would compare if the provided PIN with the one issued to the phonenumber (the number would be forwarded in the HTML form as hidden input). If it matches, user is authenticated, otherwise not.

Really nothing fancy.

**Comment by bluewavenet** [comment]
@meta-space 
Can I assume you are at the stage of successfully running opennds on the pi, such that clients can connect, get the splash page sequence and are then granted Internet access (through the modem)?

This is the essential first step ;-)

Please state:
- What version of pi hardware are you using?
- What version of OpenWrt  are you using?
- What version of openNDS are you using?

> It is [..] hooked up to an GSM/LTE modem to send the text messages

If you know or can find out how to send text messages from a [b]ash script, then the job is a relatively trivial one.

Take a close look at /usr/lib/opennds/login.sh

openNDS calls this when a client connects and it is this script that generates the html for the login page sequence.
Let me know if it makes sense to you.
This is where you will add the code to send the sms message.

**Comment by meta-space** [comment]
> Can I assume you are at the stage of successfully running opennds on the pi, such that clients can connect, get the splash page sequence and are then granted Internet access (through the modem)?

Yes, everything is setup. All the pieces work individually. 

It's an RPI4, I'd have to check the exact software versions tomorrow. This is a recent installation, presumably all packages should be up-to-date.

> Take a close look at /usr/lib/opennds/login.sh

Will do. That's the script I've been looking at and the one I would have tried to customize to our requirements.

My colleague bullish on using FAS. I've looked at fas-aes.php example. The only thing I don't understand is how the php script communicates a successful (or failed) authentication back to the NDS system.

**Comment by bluewavenet** [comment]
@meta-space 
If it is an Rpi 4, then it is most likely openNDS 8.1.1 you are running. If not you should upgrade to this.
The 8.1.1 version of login.sh is much easier to understand and make modifications to.

The FAS scripts included are:
1. login.sh - must run locally, this is the default script, uses b64 encoding, minimal required resources and no additional dependencies. 
2. fas-hid.php - can run locally or on a remote server, uses b64 encoding, minimal required resources and no additional dependencies if a remote FAS server is used but requires its own web/php server if used locally . 
3. fas-aes.php - can run locally or on a remote server, uses aes encryption and has numerous additional dependencies.
4. fas-aes-https.php - must run on an Internet hosted https server with valid tls certificates, uses aes encryption and has additional dependencies but is the most secure implementation.

For a stand alone system you can use 1, 2 and 3 above.

FAS scripts can communicate with openNDS in one of three ways:
1. Direct socket communication (usually via ndsctl calls) (eg v8.1.1 login.sh)
2. Using the GET authaction method (eg v8.1.1 fas-hid.php)
3. Using the openNDS authmon daemon for NAT traversal (eg v8.1.1 fas-aes-https.php)

**Comment by meta-space** [comment]
Turns out we're using OpenWrt which was still is locked at openNDS v5.2

Nonetheless, thanks to quick and thorough support we got it working!!

After I had looked at the current version (v8.1.1) of fas-aes.php and understood the program flow, it was quite straightforward to adapt the older (v5.2.x) fas-aes.php to our needs

**Comment by bluewavenet** [comment]
@meta-space 
I'm glad you got it working.

> we're using OpenWrt v19.07.6

As far a I am aware 19.07 does not support the Rpi4. Perhaps you have it installed as an Rpi3... The hardware might be close enough - I guess it is if it is working :-D

19.07 is approaching end of life and packages only get updated to fix bugs so yes the package repository only has an old version of openNDS.

You can, if you wish, manually install the latest version of the openNDS package if you need some of the new functionality, but otherwise it should be fine.
Let me know if you need any pointers.
