### ISSUE TITLE
where to ask questions about opennds

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#136]
is there a mailing list, or irc or something when I have a general question about OpenNDS?

I need run opennds on an openwrt router, don't really think I need remote-FAS or local-FAS(i.e. PreAuth, per the document, PreAuth is still part of FAS with a local webserver)

It seems BinAuth can do everything without FAS(be it remote FAS or PreAuth local FAS), to make life simpler, can I just use BinAuth solely? especially why do I need PreAuth at all if I only have one Openwrt router.

I'm confused by what PreAuth brings in practice as BinAuth can do all it can do locally, when do I must use PreAuth? Is it really for larger scale multiple openNDS installations on multiple gateways?

Thanks a lot.

**Comment by laoshaw** [comment]
to use BinAuth-solely I must turn on splashpage which is legacy and deprecated, does that mean in the future I must use FAS(PreAuth)? 

Assuming the legacy splash html page is removed sometime, I will need modify login.sh to produce a html just like the sitewide html to work with binauth and it will function the same as binauth+legacy_splash html?

**Comment by bluewavenet** [comment]
@laoshaw 
It is best to ask questions here - even if strictly not an issue, if you have a question then of course it is an issue for you! ;-)

I posted in another issue earlier today about FAS/PreAuth/Binauth. Here it is again ...

To clarify:

*  FAS (Forward Authentication Service) is the API that allows customisation of openNDS.
*  FAS will be code that can run remotely on the Internet, remotely on another local device, or locally on the openNDS device.
*  PreAuth is a special local FAS that uses the openNDS built in web server.
*  BinAuth is a post authentication processor, most often used for providing local logging services when the FAS server is remote.

PreAuth replaces the deprecated "templated html splash page" enabling dynamically generated html instead of the old fixed html files. **PreAuth does not need a separate web server**, it uses the built in openNDS web server just like the old splash page did.

Historically, BinAuth **was** the only way of doing a username/password login and was very restrictive and still required the static splash.html page dating back to the old NoDogSplash days.

BinAuth is now a means of getting openNDS to run a local program after openNDS authentication.

> when do I [..] use PreAuth?

**PreAuth is the default mode for openNDS and does not require the additional resources** that a full implementation of a FAS requires (eg a full FAS needs a separate web server, PHP support, more storage, more memory etc.).

_**Note: The old legacy static splash.html page support is deprecated and is removed all together in the upcoming openNDS version 9.0.0**_

> [Will I] need modify login.sh to produce a html just like the sitewide html to work with binauth and it will function the same as binauth+legacy_splash html?

No, or only a trivial change from username/email to username/password.
login.sh is specifically designed to replace the old sitewide/binauth code.

Make sure you are running openNDS v8.1.1, the login sh included there has been refactored to make the execution flow much easier to follow and therefore modify.
(if you need instructions for upgrading, just ask)
