### ISSUE TITLE
HTTP status code 511 returned

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#137]
I type http://example.com, which triggers portal detection. I filled out email and username(option 2) and click through the following page, when I was expecting http:example.com I saw the last page (on gnome linux) instead:

```
Network Authentication Required

Refresh

Portal Login
```

This message is from microhttpd and I don't need act on them to get internet access but this page is a surprise, is this a bug?

Note1. On android phone the last page will auto-close so I did not see the 511 page.

Note2. On an auto-triggered gnome desktop(disconnect then reconnect wifi) it works like android phone, no 511 page was seen and the last page will auto-close.

This only occurs when I manually trigger a http 80 page to get internet access.

**Comment by bluewavenet** [comment]
@laoshaw 
On a gnome desktop, the automatic CPD url is normally `http://nmcheck.gnome.org/`

The code 511 will be served if a client tries to access openNDS directly. It is possible your browser is cacheing the openNDS url in place of `http://example.com` because of some previous testing you have done perhaps?
Which browser are you using?

The page you are seeing is the "client status page". It is intentional and is available to all clients.
If you click "refresh" and are actually logged in, it will show client status and a "logout" button.
The url for this defaults to `http://status.client`

**Comment by laoshaw** [comment]
most likely it will be cache related as I'm accessing that page frequently. Thanks.
