### ISSUE TITLE
status.client on /etc/hosts has wrong ip address

### ISSUE THREAD

**Issue by laoshaw** [openNDS/openNDS#145]
when I use standalone odhcpd dhcp server on openwrt I'm having 192.168.1.1 for status.client but my gateway IP is not 192.168.1.1, this can lead to strange errors as opennds uses status.client in its iptables rules.

**Comment by bluewavenet** [comment]
@laoshaw 
openNDS depends upon Dnsmasq for client DNS (and dnsmasq-full for walled garden support).
Your gateway IP **must** be the default IP gateway for the subnet though, otherwise client capture will not work correctly.
Using odhcpd should be fine though.
Could you share some detail of your routing config?

**Comment by laoshaw** [comment]
restart opennds will append the correct new ip address but 192.168.1.1 still in /etc/hosts

```
192.168.1.1 status.client
192.168.2.1 status.client
```

**Comment by bluewavenet** [comment]
@laoshaw 
Ah yes, I see the problem.
Not really anything to do with odhcpd.
Currently, if gatewayfqdn is changed, openNDS updates the hosts file.
However if gatewayfqdn stays the same while the gateway ip changes, a duplicate hostname is added.
This is a bug - thanks for spotting it!
The work around for now is to manually edit the hosts file.

**Comment by laoshaw** [comment]
below patch fixed it for me.

```
--- dnsconfig.sh.orig	2021-04-10 12:45:12.066608127 -0500
+++ dnsconfig.sh	2021-02-21 13:02:28.000000000 -0600
@@ -45,11 +45,11 @@ elif [ "$setconf" = "hostconf" ]; then
 	gw_fqdn=$3
 	host_entry="$gw_ip $gw_fqdn" 
 	hosts="/etc/hosts"
-	fqdn_check=$(grep "$gw_fqdn" "$hosts")
+	host_check=$(grep "$gw_ip" "$hosts")
 
-	if [ ! -z "fqdn_check" ]; then
-		if [ "$host_entry" != "$fqdn_check" ]; then
-			sed -i "/$gw_fqdn/d" $hosts
+	if [ ! -z "host_check" ]; then
+		if [ "$host_entry" != "$host_check" ]; then
+			sed -i "/$gw_ip/d" $hosts
 			echo "$host_entry" >> "$hosts"
 		fi
 	else
```

**Comment by laoshaw** [comment]
this does not fix everything it seems, uci set network.lan.ipaddr=192.168.1.1 then /etc/init.d/opennds still not get the right IP, I think the $gw_ip probably need to read from `uci get network.lan.ipaddr`

**Comment by bluewavenet** [comment]
@laoshaw 
I'm looking at it now. $gw_ip is the ACTIVE gateway ip address. If you do `uci set network.lan.ipaddr=192.168.1.1`, it is not activated unless you do `uci commit network` (if you want it permanent) followed by `service network restart`
openNDS gets its ip address using the ip utility (not init.d) - ie the _active_ ip address of the gateway interface.

The issue is purely the logic in dnsconfig.sh
I have made changes and just testing edge cases.
Thanks for your input - a big help ;-)

**Comment by bluewavenet** [comment]
@laoshaw 
Try this snippet:
```
elif [ "$setconf" = "hostconf" ]; then
	gw_ip=$2
	gw_fqdn=$3
	host_entry="$gw_ip $gw_fqdn " 
	hosts="/etc/hosts"
	host_entry_check=$(grep "$host_entry" "$hosts")
	ip_check=$(grep "$gw_ip" "$hosts" | awk 'NR==1{printf("%s " $1)}')
	fqdn_check=$(grep "$gw_fqdn" "$hosts" | awk 'NR==1{printf("%s " $2)}')

	if [ -z "$ip_check" ] && [ ! -z "$fqdn_check" ]; then
		sed -i "/$fqdn_check/d" $hosts
		echo "$host_entry" >> "$hosts"

	elif [ -z "$fqdn_check" ] && [ ! -z "$ip_check" ]; then
		sed -i "/$ip_check/d" $hosts
		echo "$host_entry" >> "$hosts"

	elif [ -z "$host_entry_check" ] && [ ! -z "$fqdn_check" ]; then
		sed -i "/$fqdn_check/d" $hosts
		echo "$host_entry" >> "$hosts"

	elif [ -z "$host_entry_check" ]; then
		echo "$host_entry" >> "$hosts"
	fi

	exit 0
```

**Comment by bluewavenet** [comment]
@laoshaw 
Seems fixed with this. Previously, changing gw_fqdn was fine but changing gw_ip messed up.
Probably not a bad idea to manually clean up your hosts file to get rid of any bad entries.
Don't forget after changing the gateway ip address to reboot to reset everything and allow clients to get new ip addresses from dhcp.

**Comment by laoshaw** [comment]
Thanks for the patch. I did a quick test. If I have a mistake line "192.168.9.1 status.client" the current snippet won't clean it during reboot or restart-opennds and  I will still end up with two status.client lines with different IPs, it really should clean that up as that could stop opennds from working.

maybe opennds should restart-network too (it restarts firewall anyways) to make sure $2 gw_ip is up to date, that's not critical as whenever you change networking setting, a uci-commit and network-restart should be followed so it's not really opendns' responsibility, but the script does need cleanup any gw_fqdn lines that have a different IP no matter how they're added in /etc/hosts, as that could be fatal?

**Comment by bluewavenet** [comment]
@laoshaw 
The new version of dnsconfig will not put two entries in hosts. The old version could in some circumstances and that is now fixed.
If there are two or more entries, it is the first that takes effect.
If someone or something adds entries to hosts in error, then that is the problem of the person or thing that did it.

Multiple entries will not stop openNDS from working, just potentially stop http://status.client:80 being redirected to gw_ip:gw_port.

Normally, openNDS will only write to hosts on first startup after installing. Thereafter it will only update hosts if gw_fqdn or gw_ip are changed, and then only on a restart.

It should not "clean up" as entries by something else may be intentional. 

This is why I said:

>  Probably not a bad idea to manually clean up your hosts file to get rid of any bad entries.

If the gateway ip address is changed, it is pretty much essential to reboot to make sure as much as possible picks up the change,
including forcing clients to get a new ip address via dhcp. 
Even then some firewall settings could be in need of manual fixup - depends on what had been added with the old ip.

**Comment by laoshaw** [comment]
Great. Thanks!
