### ISSUE TITLE
 How to Remove Confirmation Page when using openNDS

### ISSUE THREAD

**Issue by DMiess** [openNDS/openNDS#193]
Earlier this year I began using your openNDS software in a project I’m working on to provide captive portal functionality. My desired use case is to have Wi-Fi clients log onto my device and be presented with a splash page where they need enter their e-mail address and then press a button. Upon that button being pressed they will then be redirected to the page they were trying to access (or in the case of the Windows laptop I’m testing with, msn.com).

Originally I used openNDS 7.0.1 to implement this workflow and that worked out great. However I saw the development on the project, in particular with the new themespec files and so I figured it would be prudent to upgrade. I’m in a place now where I’ve been able to get my previous use case working again except for the fact that after clicking the button on the landing page the user is directed to a page that confirms they have been authenticated. How would I be able to skip this confirmation page and simply redirect the user to the URL they were attempting to access?

When a user clicks the button on the landing page I can see that it sends the following string in the GET request (decoded from base64) so theoretically openNDS should know the address to redirect to:
hid=e423943a3e2066b5f133319a9c42ee48cf706df9aec79acf8b4b614727a1b5e0, clientip=192.168.17.100, clientmac=f8:59:71:b8:78:51, gatewayname=openNDS, version=9.1.1, gatewayaddress=192.168.17.31:2050, gatewaymac=00:14:3e:27:4f:70, originurl=http%3a%2f%2fwww.msftconnecttest.com%2fredirect, clientif=uap0, themespec=(null), (null)(null)(null)(null)

Any help would be much appreciated.

**Comment by bluewavenet** [comment]
@DMiess 

> How would I be able to skip this confirmation page and simply redirect the user to the URL they were attempting to access?

This can be done but is not of much use because the CPD (captive portal detection) found in just about all devices these days, uses a special detection url to test connectivity. This triggers the initial redirection to the login page. After authentication, most implementations close the popup CPD browser window with at best a brief flash of the text "success" in the top left, or more often a brief flash of a blank screen.

This is why the ThemeSpec login sequence has 3 stages, Login, Thankyou and Landing. Most people will only briefly see the Landing page if at all. 

The thankyou page will normally stay as long as the user does not click continue, so this can be used to show information or advertising.

If you could explain more about why you want this it may be of help. Note that at the time of writing the current release is v9.2.0 with v9.3.0 not far away.

**Comment by DMiess** [comment]
@bluewavenet

Thanks for your reply. Testing with my cellphone I can see that the browser window is closed after authentication but this is not the case on my laptop. When using the previous version of openNDS I would authenticate with my laptop and then be redirected to http://www.msftconnecttest.com/redirect which in turn would redirect to msn.com. In my use case I find this to be a more fluid user experience. As well, the way I have structured my landing page, all the information the user needs can already be found on the initial page so I have nothing left to communicate to users after they have authenticated.

Can you please elaborate on how I would recreate this single page login behaviour?

**Comment by bluewavenet** [comment]
@DMiess 

> I would authenticate with my laptop and then be redirected to http://www.msftconnecttest.com/redirect 

This is one of many of the CPD detection urls used by MS Windows. Whether the popup closes or not depends on versions and patch levels of browser and/or the Network Manager. Most implementations will close. I believe there is a registry setting to control this....
Bare in mind that a typical public captive portal will be used by clients with the following operating systems:
 * iOS ~ 70%
 * Android ~28%
 * MacOS ~ 1%
 * Linux ~ 1%
 * Windows - very rare.
 

> Can you please elaborate on how I would recreate this single page login behaviour?

Yes. But first you should upgrade to v9.2.0

Then configure to run the theme_user-email-login-basic ThemeSpec.
I will then go through the basic methods for modifying the splash sequence (ie editing the ThemeSpec)

**Comment by bluewavenet** [comment]
@DMiess 
A quick workaround to get you going might be to just use the script you had working with v7.
This will _probably_ just work.
Assuming you modified the old login.sh script, do:

```
uci set opennds.@opennds[0].login_option_enabled='0'
uci set opennds.@opennds[0].preauth='/usr/lib/opennds/login.sh'

```
Then test after restarting opennds:
`service opennds restart`

Finally if you are happy with this, commit the config changes:
`uci commit opennds`

If it is _not_ working correctly then do:

    `uci revert opennds`

  followed by:

      `service opennds restart`

The v9.x ThemeSpec files are specifically designed to make customisation easy, so it is well worth getting familiar with this for further development purposes, the reversion back to your old script file should only be regarded as a workaround.

**Comment by DMiess** [comment]
@bluewavenet,

I agree with you that it would be better to use the new themespec way of doing things rather than to fall back on using the old login script. It is good to know though that that is an option if all else fails. I've switched over to openNDS 9.2.0 and switched to using theme_user-email-login-basic.sh as my themespec. Can you elaborate on how I would go about getting the behaviour I'm looking for?

**Comment by bluewavenet** [comment]
@DMiess 
Make a copy of themespec file theme_user-email-login-basic.sh in the folder /usr/lib/opennds/
Name it something recognisable eg. my_basic_email_login.sh

Run the commands:
```
uci set opennds.@opennds[0].login_option_enabled='3'
uci set opennds.@opennds[0].themespec_path '/usr/lib/opennds/my_basic_email_login.sh'
service opennds restart
```
Test to see if it is working exactly as before and if it is then do:
```
uci commit opennds
service opennds restart
```

Now open your new themespec file in a suitable editor.

When a client CPD triggers openNDS (by attempting to access a detection url), openNDS first imports data and theme specification from the themespec file to begin generating html code to be served to the client. 

The next step is where we are interested. openNDS does a call to the themespec function `generate_splash_sequence()`

You will find this at line 14 of the unchanged file.

As this is a copy of the theme_user-email-login-basic script, you can see the function name_email_login() is called next.

If you follow the code you will see the user login form html is generated, asking for username and email address.

Note the form action is:
`		<form action=\"/opennds_preauth/\" method=\"get\">`

This means that when the client clicks continue they are redirected back to openNDS in a loop where client input is checked and decisions are made what to do next.

It is simple to edit the html code (each section is labelled accordingly).

Make some simple changes and test so you see the change. In this way you should rapidly gain understanding of the logic.

Let me know your progress.

**Comment by DMiess** [comment]
@bluewavenet 

I went through the procedure you provided but the result seems pretty similar to what I had setup previously. When I switched to openNDS 9.x.x I based my splash page on theme_click-to-continue-basic.sh rather than theme_user-email-login-basic.sh but the structure seems to be comparable. I understand the general formatting about how the pages are created but I'm still uncertain on how to redirect rather than bringing up a thank-you page.

Playing around with it a bit I've been looking into serving a separate header in the case where $landing == "yes" that has an HTML redirect in the <head> section based on the $originurl variable. Does this seem like the right path?

**Comment by bluewavenet** [comment]
@DMiess 
Following the simple logic in the script and choosing the parts you need is the best way forward, the standard ThemeSpec files are well self documented - I am quite happy to give you hints and to help you understand, but you should read through it all yourself first. You will find it easy to design a splash page sequence that matches your requirements.

However there is a fundamental issue with what you have so far indicated is your requirement.

To prevent us wasting time I think that before going any further we should review your requirement and if necessary adjust it to enable a good solution to be developed.

This is what I understand so far:

 *  > a splash page where they need enter their e-mail address and then press a button.
 
The theme_user-email-login-basic script is a good place to start as it already asks for email address. If desired, removing the username field is a trivial edit.

 * > Upon that button being pressed they will then be redirected to the page they were trying to access

This is easy to achieve, but for almost 100% of clients connecting to a "Public" WiFi, this will result in a very poor user experience, leaving people for the most part wondering what happened and thinking the system does not work or is broken.

Yes, I understand this works with **your** Windows machine, but, in my experience, this is **not** the default behaviour of Windows (from version 7 onwards, I believe Network Manager CPD was enabled...)

**Comment by DMiess** [comment]
@bluewavenet 

As far as requirements I'm looking to replace the behaviour I had on openNDS 7.0.1 where I would automatically be redirected after logging in on the splash page. This behaviour fits the requirements that I'm looking for both on Windows and on mobile devices. 

I've implemented the solution I was thinking about in the previous comment where I change the header of the page being served based on the $landing variable in order to add a redirect to the $originurl. However there's still something different about the behaviour when compared with the earlier release. When I use my solution on the earlier release and log in with a Windows laptop I am always redirected to http://www.msftconnecttest.com/redirect. However when I'm using the new 9.x.x solution I'm redirected to http://www.msftconnecttest.com/connecttest.txt or a similar URL from Mozilla. I know that this must be a result of the different behaviour between the openNDS versions because that's the only difference between the two cases. Do you know what might be causing this different behaviour?

**Comment by bluewavenet** [comment]
@DMiess 
A quick bit of research leads me to think that the Windows Updates replaced the CPD detection url  `http://www.msftconnecttest.com/redirect` by the standards compliant `http://www.msftconnecttest.com/connecttest.txt `

This is verified by looking at the logs of a very busy production site, where instances of the use of the /redirect version have all but disappeared. I am sure someone more versed in the history of Windows Updates could shed some light on this.

> I know that this must be a result of the different behaviour between the openNDS versions

This is not the case at all.

CPD is "code" that lives on the client device. All mainstream operating systems and all mainstream web browsers have an implementation of CPD built in.

In operating systems this is usually part of the "Network Manager" or equivalent.
When a client detects a new wireless connection its CPD tries its detection url, which in turn triggers a captive portal if present.

On desktop and laptop class devices, the CPD will re-test for connectivity at a pre set interval, often set to something like 300 seconds.

On "smartphone" and "tablet" class devices however, re-tests are disabled as this consumes a significant amount of battery capacity if the device is otherwise sleeping, as is the case very often after the initial flurry of activity at a public venue such as a coffee shop for example.

Browsers also have built in CPD. This functions in exactly the same way as the Network Manager implementation.
This is very useful in that it interleaves with the Network Manager giving a faster re-connect if the client is logged out (for example after reaching its session end time).
On mobile devices, browsers do not usually run in the background and are put to sleep when the device sleeps, so the battery consumption issue is averted.

This explains why sometimes you see the Microsoft Network Manager test url, and sometimes see the Mozzilla test url (presumably from the browser you have open).

openNDS is **only** triggered by the client attempting to access a port 80 url and this is determined by the client CPD.

The only exception to this is if the client user opens a browser and attempts to access the openNDS url directly, thus generating an Error 511 page, which will have a login button. This page uses the Mozzilla detection url. 

**Summary:**
To provide a consistent and friendly user experience, openNDS serves a 3 stage splash page sequence.
The "Third", or "Landing" page is displayed as a consistent confirmation that login has been successful. Most CPD mobile implementations will automatically close this page within seconds, but for those that do not, the page can carry additional information and has a continue button to go to the originally requested url, although this is mostly of little use as it will be a blank page or just say "success" or similar.

**Comment by DMiess** [comment]
@bluewavenet 

I can certainly appreciate that the captive portal detection is something that is being handled by the client device, whether it be through the system's network manager or through the web browser. My observations though lead me to strongly suspect that openNDS is having an effect on the way the process goes through, particularly with the redirect after authentication.

I'm not sure offhand what particular version of Windows 10 I'm running or whether it is affected by this deprecation of http://www.msftconnecttest.com/redirect or not but testing today I can see a difference using this Windows laptop between openNDS 7.0.1 and openNDS 9.2.0. In the case of openNDS 7.0.1 every time I authenticate I am redirected to the previously mentioned URL but when I then switch over to openNDS 9.2.0 I no longer get this redirect. Given that everything else about these two test cases is the same I have to imagine that it's openNDS that's responsible for the difference in behaviour.

From our conversation I'm getting the impression that you are strongly in favour of migrating to the three stage splash page sequence. If you don't want to bring back support for the previous splash page + redirect behaviour I had (and there is no way to configure it today) please just let me know and I'll migrate to the new workflow.

**Comment by bluewavenet** [comment]
@DMiess 

> you are strongly in favour of migrating to the three stage splash page sequence

Yes, because it gives the best user experience

Here is an example of the landing page on my laptop (running OpenSuse Linux). openNDS is using the theme_user-email-login-custom-placeholders script with the example info/ads.

It is displayed by the Gnome Network Manager. You can clearly see the text above the Continue button:
```
Your device originally requested http://nmcheck.gnome.org/ 
Click or tap Continue to go to there.
```

![landing](https://user-images.githubusercontent.com/13632068/127221788-8d4d5498-f2af-433f-a18b-38b1d671188e.jpg)

In this implementation of CPD, the landing page stays up until the user clicks Continue.

> the previous splash page + redirect behaviour I had (and there is no way to configure it today)

Yes there is - by using raw PreAuth - I mentioned this earlier, if you really must you could use a modified version of your original login script.

> I'll migrate to the new workflow

I would recommend that you do, purely for the user friendly experience, but it is totally up to you.

You can of course modify landing_page() to set $originurl to anything you like eg msm.com, either for everyone or by mac address. 
However if I connected to a venue wifi and found myself redirected to msn.com, I would be very disgruntled!

**Comment by DMiess** [comment]
@bluewavenet 

Thanks for your help. I'll go ahead and adjust to using the new three stage splash page behaviour.

Daniel
