### ISSUE TITLE
Question about walled garden

### ISSUE THREAD

**Issue by richyxi** [openNDS/openNDS#196]
Hi! I'm thinking about integrate google ad sense on the cpd of the devices. For my understanding is that you can add a piece of code in the html body so you get an ad when you access the site, then is up to you if you want access or not to the advertiser site.

Sample:
`<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1234567890123456" crossorigin="anonymous"></script>

<ins class="adsbygoogle"
style="display:inline-block;width:728px;height:90px"
data-ad-client="ca-pub-1234567890123456"
data-ad-slot="1234567890"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
`

In this particular case, is necessary to have the fqdn's of google and it's advertisers? If yes, wouldn't be easier to allow the all traffic?.

Also, is there a proper method to get fqdn's for the external sites?

Thanks in advance!

**Comment by sicelo** [comment]
Nothing prevents you from adding AdSense on your pages.

Examples for adding the fqdns - https://opennds.readthedocs.io/en/stable/config.html#autonomous-walled-garden-configuration

However, bear in mind that the CPD will usually auto-close the browser window once it detects that there is working Internet. Additionally, the operation of Javascript and similar technologies may be limited, or absent in the CPD browser.

**Comment by bluewavenet** [comment]
@richyxi 
Just to clarify:
The CPD is a part of the client operating system and as such openNDS has no control over it.
Almost all operating system CPD implementations prohibit the downloading of any files. Otherwise if allowed, just connecting to a captive portal will be enough to force a download of anything to the client device. Obviously this would be the worst kind of security issue and could open the door to all sorts of hacking exploits, particularly if the download was code to be executed by the client CPD.

**Comment by richyxi** [comment]
So en theory, there will be devices who can actually download js code and other that don't? 

Also, if I want to add the snippet 

`<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1234567890123456 crossorigin="anonymous"></script>`

The fqdn of that source will be pagead2.googlesyndication.com?

**Comment by richyxi** [comment]
Okay great. Thanks for the info and your time!
