### ISSUE TITLE
authmon propose

### ISSUE THREAD

**Issue by Scyllaly** [openNDS/openNDS#218]
https://opennds.readthedocs.io/en/stable/fas.html#manual-access-of-nds-virtual-url

Origin text:
```
http://fasremoteip:fasport/faspath?clientip=[clientip]&gatewayname=[gatewayname]&status=authenticated
```

Recommand:
```
http://fasremotefqdn:fasport/fas_post_path?clientip=[clientip]&gatewayname=[gatewayname]&status=authenticated
```

#### reason
- FAS running on LEVEL 3 (fas_secure_enable = 3)
- fasremoteip ---> fastremotefqn
  Because of FAS running on a VPS, it has much other site use one ip (different domain use same http port , like 80) , or the domain use CDN
- faspath ---> fas_post_path(or authmonpath??), Add one new option in OpenNDS, when i create a new FAS by laravel , i set the option `faspath` to `/` , set the laravel's router  `/`,  when user send a `GET` request, it normal shows the login page (view), and when user send a `POST` request, it will auto Validate the POST data is valid or not , i use Form Validator in laravel (auto validate the post data). If possible, divide the path into two,  it will convenient for developers to distinguish between gateway requests and user requests

**Comment by bluewavenet** [comment]
@Scyllaly 
Sorry I do not understand what you are proposing.

Some comments:
 * Defining fasremoteip and fasremotefqdn allows access to a shared server that may be hosting many web sites.
 * A VPS (Virtual Private Server) is private and not shared by default. Access could be by fasremoteip alone, but is nicer if fasremorefqdn is also defined.
 * A CDN is a single logical server distributed over many physical servers. It is similar to a shared server but requires fasremotefqdn to be configured into the openNDS walled garden.
 * Clients always send GET requests to FAS, they cannot do anything else because they are redirected to the FAS url with a query string. It is not possible to redirect with a POST request.
 * Authmon always sends POST requests.
 * It is very simple in PHP to differentiate between GET and POST requests in a single PHP script, as can be seen in the example fas-aes-https.php
 * I cannot see the purpose of having a separate fas_post_path for authmon

**Comment by Scyllaly** [comment]
I have solved this problem. Thank you for your answer
