### ISSUE TITLE
VERSION 4.x CAN'T INSTALL

### ISSUE THREAD

**Issue by giro0710** [openNDS/openNDS#25]
**I can't install NDS/openNDS to my TP-Link TL-MR3420v5 router since version 4.x has released.** Anyone, please help me fix this or suggest new router brand/model that will work on version 4.x or later

**Comment by bluewavenet** [comment]
@giro0710 
Download the latest release (v5.1.0 at the time of writing), from:
https://downloads.openwrt.org/snapshots/packages/mipsel_24kc/routing/opennds_5.1.0-1_mipsel_24kc.ipk

Copy to /tmp
Run:
`opkg install /tmp/opennds_5.1.0-1_mipsel_24kc.ipk`

Then run the commands:
```
uci set opennds.@opennds[0].use_outdated_mhd='1'
uci commit opennds
service opennds restart
```
You do not say which version of OpenWrt you are using, but all current "stable" releases have an outdated version of the libmicrohttpd (MHD) library that _can_ corrupt usernames and passwords if used in PreAuth or BinAuth. If an outdated version of MHD is detected, openNDS will terminate unless forced to use it with the use_outdated_mhd option.

The TP-Link TL-MR3420v5 is a legacy device with low flash and ram capacity.
However it should be ok with openNDS templated splash pages and FAS-PreAuth. A local FAS (other than PreAuth) is probably too much for it.

Any OpenWrt supported device with 16MB flash or greater and 128MB ram or greater would be recommended for future development.

**Comment by giro0710** [comment]
Got this error while installing:

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for opennds:
 *      kernel (= 5.4.48-1-5a61a17a6967a7071803cea568492bf9) *
 * opkg_install_cmd: Cannot install package opennds.

I'm using firmware version **LEDE Reboot SNAPSHOT r5442+6-b0b289e / LuCI Master (git-17.328.04231-802d5b6)**

**Comment by bluewavenet** [comment]
@giro0710 

This is your problem:
> LEDE Reboot SNAPSHOT r5442+6-b0b289e

You have an extremely old "daily" snapshot that was most likely outdated within 24 hours of being downloaded. openNDS is trying to install a missing kernel module for iptables and it cannot find that old snapshot repository.

Do you have a reason for running this old unreleased LEDE version?

I would suggest reflashing with OpenWrt 19.07.3 - but make sure you **_do not keep the old configuration_** as this will almost certainly result in failure as so much has changed since the LEDE snapshot you have currently, particularly the wireless drivers.

Download:
https://downloads.openwrt.org/releases/19.07.3/targets/ramips/mt76x8/openwrt-19.07.3-ramips-mt76x8-tplink_tl-mr3420-v5-squashfs-sysupgrade.bin

Copy to /tmp
Then run:
`sysupgrade -n /tmp/openwrt-19.07.3-ramips-mt76x8-tplink_tl-mr3420-v5-squashfs-sysupgrade.bin`

After this you should configure as desired (eg IP address, SSID etc) before continuing with the installation of openNDS v5.1.0 as described earlier.
