### ISSUE TITLE
New iptables rate limiting approach not working reliably

### ISSUE THREAD

**Issue by T-X** [openNDS/openNDS#259]
With the previous TC based approach we could achieve a smooth TCP traffic flow at around the specified limit at any time. However with the switch from TC to iptables `--limit` based rate limiting this does not work well anymore. With a global upload + dowload rate configured to 1000 kb/s:

* Initially, no rate limit is applied. It'll take up to the configured checkinterval until any rate limiting is applied (60 by default)
* Then when the rate limit is reached, after 83 packets, traffic is cut off completely
* No traffic will flow for about 25 seconds
* Then another batch of 83 packets can flow through again. (see iptables man page and "--limit-burst" paramter, 5 packets will be recharged per second by default)
* Then again no traffic for 25 seconds
* repeat

This was tested with iperf3.

From searching on the net I could only find examples for iptables `--limit` which try to limit the number of connections, so usually on TCP SYN packets for simple DoS protection. But I couldn't find any example which use iptables `--limit` for traffic shaping. Maybe it's not quite suitable for this job?

Edit: With UDP traffic it seems to be worse: With the 1000 kb/s limit and a constant 50 MBit/s iperf3 UDP stream there are only a few packets that make it every 5 minutes or so.

**Comment by bluewavenet** [comment]
@T-X 
Thank you for the testing you have done - always appreciated.
It would be good to know which openNDS version you are using, the current release is 9.4.0, with 9.5.0 in beta testing.

> With the previous TC based approach we could achieve a smooth TCP traffic flow

That was a very long time ago, Traffic Control (in what was then Nodogsplash) has been broken since the release of OpenWrt 12.09 (Attitude Adjustment).

openNDS implements both volume and rate quotas per client. This is more for the  purposes of fair usage of available bandwidth for all clients rather than the smoothest form of "Traffic Shaping"

Volume quotas:
Very briefly, when a client exceeds their volume quota, they are deauthenticated. It is the responsibility of the FAS system to manage whether a client has to wait before logging back in or not.

Back to rate quotas:
Rate quotas use a moving window average calculation for data rates for each client. The window size is the product of checkinterval (default 60 seconds) and ratecheckwindow (default 2). So by default a client data rate is first calculated after 120 seconds have passed. This allows a client to "burst" at full rate. This provides for a good user experience allowing rapid email synchronisation etc on first connecting.

If the calculated value does not exceed the quota, nothing happens.
If it does exceed the quota then the client is rate limited (download and upload are treated independently).
The rate limiting is done at a calculated number of packets per second based on a packet size of 1500 bytes.
This is implemented using iptables --limit with conntrack support. 

At each checkinterval * ratecheckwindow period, the clients current average rate is recalculated and if it drops below the rate quota, rate limiting is lifted.

Setting debuglevel to 2 and monitoring syslog is a good way to see what is happening.

Typical users of a captive portal at a public venue want their emails, want to browse, use social media, upload photos, stream music or video etc etc. All of these things have bursty traffic profiles and the iptables limit approach handles all of these very well, for the most part users will be unaware of it. Even torrenting works well, albeit with potential high levels of retries.

**All of this is achieved without additional dependencies.**

However using iperf3 will push the dropped packet rate very high with long pauses as the iptables bucket filter tries to keep up. 

> a constant 50 MBit/s iperf3 UDP stream there are only a few packets that make it every 5 minutes or so.

Absolutely! This is about providing a good user experience for guests and customers at public venues. Constant 50MBit/s UDP streams are not to be encouraged at public venues with limited bandwidth Internet feeds. 

> Maybe it's not quite suitable for this job?

It is suitable for most public venue situations.
There is scope for tuning using checkinterval * ratecheckwindow variations, and there is probably an argument for an enhancement to allow limit-burst to be set as a config option.

If something better is required for specific special situations, something like SQM scripts works very well, particularly if working on the openNDS interface rather than the WAN interface of the router.

**Comment by bluewavenet** [comment]
@T-X 
FYI, v9.5.0 will have the option of specifying upload and download bucket ratio values. 
This allows tuning of bucket size (queue length) for rate quotas at the expense of ram consumption per client.
You can tune to minimise dropped packets in scenarios where the client exceeds the rate limit threshold. You can eliminate dropped packets by ensuring the queue is big enough to hold the "bursting" packets. Packets from a continuous stream however will ultimately always be dropped.

**Comment by T-X** [comment]
> That was a very long time ago, Traffic Control (in what was then Nodogsplash) has been broken since the release of OpenWrt 12.09 (Attitude Adjustment).

We can't confirm that. At least with these added three patches:

https://github.com/T-X/openNDS/tree/opennds-8.1.1-tc-fixes

And we had two independent parties test and confirm that rate limiting works well with this.

Thanks for your effort, with the bucket size option in v9.5.0. Sorry for my directness, but this feels like a workaround for an inadequate choice in the first place. TC is exactly designed for this and gives exactly the results you'd expect. If you set 10/10 MBit/s tc limits for example, it'll 99% behave like an 10 mbit/s ethernet device. The addition and removal of iptables rules on specific intervals is kind of... clunky and erratic.

We were in the process of updating to v9 to be able to better contribute to upstream. As you rightfully remarked in one of the previous tickets that it's difficult to accept patches which were only tested on v8. Which I totally agree with you. Unfortunately the removal of TC seems like a blocker for us to migrate to v9 to me at the moment.

**Comment by bluewavenet** [comment]
@T-X 

> 
> 
>     That was a very long time ago, Traffic Control (in what was then Nodogsplash) has been broken since the release of OpenWrt 12.09 (Attitude Adjustment).
> 
> We can't confirm that.

See: https://github.com/nodogsplash/nodogsplash/issues/316

Both tc and iptables can configure the kernel traffic flow.
Yes, tc is very sophisticated with many possible tuning options.
But it openNDS would have several additional dependencies for built in support, something to be avoided if possible as many target devices can be resource limited.

On the other hand, iptables can be used to implement rate limiting on a per user basis without installing any additional packages, albeit without the range of options available with tc.

On considering the requirements for rate limiting in openNDS, two essentials were identified for the majority of use cases:
1. Good user experience where normal bursty traffic such as synchronising email with remote mail servers, social media image uploads etc is expected.
2. Fair usage of available Internet feed bandwidth.

Requirement 1 is met by allowing unrestricted usage for short intervals before rate limiting, thus enabling for example, very rapid email syncing.

Requirement 2 is met using the iptables token burst filter (--limit --limit-burst).

These requirements can be met using iptables alone. The decision was made to integrate this method into openNDS.
**_It works well and reliably_** and is far from being clunky and erratic

The test results in your original post would be very similar if using tc:

> With the 1000 kb/s limit and a constant 50 MBit/s iperf3 UDP stream there are only a few packets that make it every 5 minutes or so.

Regardless of the choice of iptables or tc, a stream that is 50 times the allowed rate will overflow available queues almost instantly, dropping the vast majority of packets.

The built in openNDS rate limiting can be disabled. Any other method could be implemented using hooks available in FAS although there is scope for making this a configurable option.

**Comment by T-X** [comment]
> @T-X
> 
> > ```
> > That was a very long time ago, Traffic Control (in what was then Nodogsplash) has been broken since the release of OpenWrt 12.09 (Attitude Adjustment).
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can't confirm that.
> 
> See: [nodogsplash/nodogsplash#316](https://github.com/nodogsplash/nodogsplash/issues/316)

In this ticket and other sub tickets referenced in there it seems to me that either people have not tested it or had trouble finding the correct modules to install. Our TC related dependencies in the openNDS OpenWrt Makefile look as follows on OpenWrt 19.07:

```
...
define Package/opennds
        SUBMENU:=Captive Portals
        SECTION:=net
        CATEGORY:=Network
        DEPENDS:=+libpthread +iptables-mod-ipopt +libmicrohttpd-no-ssl +libradcli +libjson-c +tc +kmod-sched-core +kmod-sched-connmark +kmod-ifb +libnl-tiny \
                +!BUSYBOX_CONFIG_BASE64:coreutils-base64
        TITLE:=Open public network gateway daemon
        URL:=https://github.com/opennds/opennds
        CONFLICTS:=nodogsplash nodogsplash2
endef
...
```

(ignore the added libjson-c, libradcli and libnl-tiny dependencies for now)

This PR here from @drwyrm, which was merged: https://github.com/nodogsplash/nodogsplash/pull/155

And according to @drwyrm TC was working with that. And that works well for us, too. So I'm still confused. I don't see any feedback from you or @mwarning that you'd tested this PR. So how do you know that it's not working then?

**Comment by bluewavenet** [comment]
> I don't see any feedback from you or @mwarning that you'd tested this PR. So how do you know that it's not working then?

It requires the additional packages and there was very little or zero demand for it, with sql scripts being satisfactory for the few cases where something was required - so no one ever tested it, or at least no one reported that it worked.
It is worth remembering that back then the most popular target hardware would be in the 8/32 flash/ram or smaller range such as the Ubiquiti Bullet and similar, so resource limitations were more of a concern than they are today, but even now 16/128 devices are the most popular for small venues.

**Comment by drwyrm** [comment]
Hey guys, been a long time since I worked on this and I don't have all the
details on the current iptables based implementation, so, keep this in mind
while reading.

The TC based code works just fine, it does smooth traffic shaping in real
time, with no noticeable dropouts, and works perfectly even for very low
limits (<50kbit/s). TC is THE tool for this.

As far as I know, iptables --limit wasn't made for traffic shaping at all.

My PR (and IFB) works with SQM without any problems, this includes sqm
scripts from Openwrt, as long as sqm scripts are configured correctly on
the proper upstream interface (not downstream). My PR sets up SQM for
downstream **per client**, so, sqm downstream isn't needed from other
sources.

As far as I remember, the only added dependency on my PR was kmod-ifb.

Em sáb., 20 de nov. de 2021 20:32, Rob White ***@***.***>
escreveu:

**Comment by bluewavenet** [comment]
@drwyrm 
Thank you very much for coming back here and giving your input.
A tc based solution will work well, that is not disputed. Such a solution can potentially have many powerful tuning options to give the best results for any scenario.

But for **_built in rate quota support,_** openNDS has requirements to be met, mentioned above but listed here in a more definitive way for clarity:
1. Additional dependencies to be avoided
2. Bursting at unrestricted rates (above the set quota) to be allowed for configurable intervals, with rate limiting taking effect and reducing a moving average rate to the configured level.
3. Not let 1. and 2. compromise the extendability of openNDS (using FAS and BinAuth to support add-on modules)

Item 1 in this list is to minimise the default footprint of openNDS as many target devices are somewhat restricted in resources.

Item 2 in this list is to provide a good user experience in the most common scenario of a public venue where the client is using its connection for short intervals (For example a guest in a coffee shop wants to sync emails on an IMAP server as quickly as possible)

All three requirements are met using the iptables token bucket filter support.
 * It has been extensively tested and was introduced in release 9.0.0 in May 2021
 * It is now in use in many installations and has been refined with each release since.
 * The current v9.5.0beta 50kb/s lower limit is temporary and its removal awaiting testing of minor changes to the token bucket size calculation.
 * Ultimately, the iptables method works in the same way as a tc solution, by queueing data during bursts and dropping data on queue overflow.

For others reading this, some historical info:
 * The original NoDogSplash PR was submitted in 2016.
 * It was not merged as there was at that time no mechanism to apply per user rate limiting as the legacy "binvoucher" method was no longer supported.
 * It was eventually merged in 2018 after the "new" binauth support was added, but remained officially untested with no reports of its successful use.
 * It was removed entirely from openNDS release 9.0.0 in May 2021.
 * It took six months for anyone to notice its removal despite a rapidly growing openNDS user base.

Again for others that may read this, it should be noted that, without dropping excess data, no form of traffic shaping can rate limit a continuous stream that exceeds the required limit.

There is most definitely an argument for the provision of an optional tc based add-on, potentially improving performance in a larger range of use cases. Comments would be very welcome from everyone.

**Comment by taqiyasyaml** [comment]
Hi,

Is there any documentation on how to implement TC with openNDS? (or any documentation on how to limit data rates). Because I can't limit client speed by default method (from custom value or by command ndsctl auth 192.168.19.85 0 1000 1000). I have Internet speed around 100mbit so I want to try to limit it to 1000kbit. Using speedtest (speedtest.net/fast.com), my device always get max speed around 85mbits (probably due to wireless connection) for 2 minutes then can't access for 2 minutes then get max speed again and so on.

Here is my system log

`Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Client @ 192.168.19.85 xx:xx:xx:xx:xx:xx, quotas:
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: 	Download DATA quota (kBytes): 0, used: 331796
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: 	Upload DATA quota (kBytes): 0, used: 130138
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Window start [1640097379] - window counter [1]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: in_window_start [0] - out_window_start [0]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: durationsecs [86] download_bytes [331796078] upload_bytes [130138862]
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: 	Download RATE quota (kbits/s): 1000, Current average download rate (kbits/s): 30864
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: 	Upload RATE quota (kbits/s): 1000, Current average upload rate (kbits/s): 12105
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: cp1->download_rate: 1000 downrate: 30864
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Download RATE quota reached for: 192.168.19.85 xx:xx:xx:xx:xx:xx, in: 30864kbits/s, out: 12105kbits/s
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Average Download Packet Size for [192.168.19.85] is [1267] bytes
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Download Rate Limiting of [192.168.19.85 xx:xx:xx:xx:xx:xx] to [6061] packets/min, bucket size [181023]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Executing command: iptables --wait -t mangle -D ndsINC -d 192.168.19.85 -j ACCEPT
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Setting default SIGCHLD handler SIG_DFL
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: iptables command [ -t mangle -D ndsINC -d 192.168.19.85 -j ACCEPT ], return code [ 0 ]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Executing command: iptables --wait -t mangle -A ndsINC -d 192.168.19.85 -c 261786 331796078 -m limit --limit 6061/min --limit-burst 181023 -j ACCEPT
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Setting default SIGCHLD handler SIG_DFL
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: iptables command [ -t mangle -A ndsINC -d 192.168.19.85 -c 261786 331796078 -m limit --limit 6061/min --limit-burst 181023 -j ACCEPT ], return code [ 2 ]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Executing command: iptables --wait -t mangle -A ndsINC -d 192.168.19.85 -j DROP
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Setting default SIGCHLD handler SIG_DFL
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: iptables command [ -t mangle -A ndsINC -d 192.168.19.85 -j DROP ], return code [ 0 ]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: cp1->upload_rate: 1000 uprate: 12105
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Upload RATE quota reached for: 192.168.19.85 xx:xx:xx:xx:xx:xx, in: 30864kbits/s, out: 12105kbits/s
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Average Upload Packet Size for [192.168.19.85] is [937] bytes
Tue Dec 21 21:37:45 2021 daemon.info opennds[22405]: Upload Rate Limiting of [192.168.19.85 xx:xx:xx:xx:xx:xx] to [8196] packets/min, bucket size [91021]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Executing command: iptables --wait -t filter -I ndsULR -s 192.168.19.85 -j DROP
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Setting default SIGCHLD handler SIG_DFL
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: iptables command [ -t filter -I ndsULR -s 192.168.19.85 -j DROP ], return code [ 0 ]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Executing command: iptables --wait -t filter -I ndsULR -s 192.168.19.85 -c 138741 130138862 -m limit --limit 8196/min --limit-burst 91021 -j RETURN
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: Setting default SIGCHLD handler SIG_DFL
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: iptables command [ -t filter -I ndsULR -s 192.168.19.85 -c 138741 130138862 -m limit --limit 8196/min --limit-burst 91021 -j RETURN ], return code [ 2 ]
Tue Dec 21 21:37:45 2021 daemon.debug opennds[22405]: RATE EXCEEDED flag is 3`

When I forcibly enter iptables, here is the result

`root@192.168.19.1:~# iptables -t mangle -A ndsINC -d 192.168.19.85 -c 261786 331796078 -m limit --limit 6061/min --limit-burst 181023 -j ACCEPT
iptables v1.8.7 (legacy): limit: bad value for option "--limit-burst", or out of range (0-10000).

Try `iptables -h' or 'iptables --help' for more information.
root@192.168.19.1:~# iptables -t filter -I ndsULR -s 192.168.19.85 -c 138741 130138862 -m limit --limit 8196/min --limit-burst 91021 -j RETURN
iptables v1.8.7 (legacy): limit: bad value for option "--limit-burst", or out of range (0-10000).

Try `iptables -h' or 'iptables --help' for more information.
root@192.168.19.1:~#`

Thank you

**Comment by bluewavenet** [comment]
@taqiyasyaml 
As this issue is closed, I did not notice your report. Sorry for the delay responding. It would have been better to open a new issue, but I will answer anyway.

> limit: bad value for option "--limit-burst", or out of range (0-10000).

It seems we should call this a bug. There does not appear to be any documentation of a maximum value for limit-burst so it is not restricted in the code.
It only becomes noticeable in the case of a large ratio between actual bandwidth and the required rate restriction, particularly when packets sizes are relatively small. In your case this ratio is 100, so the likelihood of exceeding the maximum bucket size is quite high.

In your case the rate restriction fails and all packets are dropped. In the next cycle, the drop rule is removed and traffic restarts. This continued off/on indefinitely as you continued with your speed testing.

If you simply want to restrict to the same rate for all clients, it might be better to use a third party package as long as your router has the resources to install and run the extra package.

See:
https://opennds.readthedocs.io/en/stable/traffic.html#traffic-shaping

I will fix the "bug" by setting the upper limit to bucket size to 10000. This will be included in the next release.
