### ISSUE TITLE
Accouting to fas

### ISSUE THREAD

**Issue by deivisonmoraes** [openNDS/openNDS#278]
Hi,

I'm implementing opennds and it's already operational using remote server (fas). Is there any way for opennds to send the accouting information to the fas server?

Tks

**Comment by bluewavenet** [comment]
@deivisonmoraes 
What accounting information do you mean?
The client account is created on the remote FAS although on the example scripts it is trivial ie it just records what the user types in.

**Comment by sicelo** [comment]
On Thu, Dec 16, 2021 at 12:44:09PM -0800, Rob White wrote:
> @deivisonmoraes 
> What accounting information do you mean?
> The client account is created on the remote FAS although on the example scripts it is trivial ie it just records what the user types in.

I think he means Accounting in AAA, à la RADIUS.

When I needed to do accounting, I found it was better/easier to use
ndsctl, i.e. to do the accounting on the router, instead of FAS, because
the FAS is not involved once the client is Authorized. I kept the usage
data in an sqlite database in the router. I haven't looked at this again
since over a year ago, and openNDS has changed in many ways since then.

**Comment by deivisonmoraes** [comment]
That's right, it's something like the radius. I migrated from wifidog to opennds and our system is oriented to information coming from the gateway like inbound and outbound traffic and I also use it to decide remotely if I want to keep the client authenticated. One idea I thought was to make a sh script to update the base remotely and so with ndsctl decide when to disconnect the client.

**Comment by sicelo** [comment]
`ndsctl` already has facility to handle quotas, so unless you have some very specialized setup, there's no need for that sh script. FAS can inform `ndstcl` what quotas to set on a client basis. Then you let `ndsctl` handle the rest.

**Comment by bluewavenet** [comment]
@deivisonmoraes 
It is not clear to me what you are asking for.
The only information a remote FAS will not have is the client quota usage on deauthenticating. Is this what you want?
If so then you can easily modify binauth_log.sh script to send the deauth data to a remote FAS.

@sicelo @deivisonmoraes 
Yes, a lot has changed since the early versions of openNDS.
The best place to set per client quotas is in FAS (be it remote or local), and not in binauth (setting in binauth is somewhat outdated - maybe that part of binauth should be deprecated as it no longer serves much purpose)

**Comment by deivisonmoraes** [comment]
@bluewavenet I actually need 2 things.
1 - Updated information on bandwidth consumption from time to time
2 - Send disconnection remotely

Sorry if I'm not able to express myself correctly...

**Comment by bluewavenet** [comment]
@deivisonmoraes 

>  1 - Updated information on bandwidth consumption from time to time

Do you mean information on bandwidth consumption for the system, or for individual clients as they use the system?
This could be in the form of a report, for example the information available from `ndsctl`, sent at some interval.

> 2 - Send disconnection remotely

Do you mean send the deauthentication log per client to FAS?
This could be the deauth log entry for the client, sent when the deauth occurs.

Neither of these are needed in normal use but if you require them, it is quite easy to write your own scripts to do it.
If you need any hints let me know.
