### ISSUE TITLE
Howto for simple Facebook WIFI for business page

### ISSUE THREAD

**Issue by PeterHanusiak** [openNDS/openNDS#288]
Hi, I am using OpenWrt on my D-Link - DIR-882 A1, where I created guest Wifi. Following OpenNDS documentation I installed openNDS and secured my guest Wifi. It uses the default OpenNDS splash screen. It was super easy and I liked it.
However I am trying to understand how I should configure a basic Facebook Wifi for a specific business page. I am talking about https://www.facebook.com/help/126760650808045/ Facebook Wifi feature and not a custom FB app with a login plugin. Facebook Wifi is a common feature for guest Wifi on a number of Wifi routers for example TP-Link Archer C50 etc.

Do you have some basic steps on how to achieve this functionality? I searched through your documentation and I could find only Walled Garden where FB IPs were handled, however I didn't find any explanation how I hook into Facebook Wifi for my configured Business page (Facebook standard functionality).
Please give me some hints on how to do it.

thank you

**Comment by bluewavenet** [comment]
@PeterHanusiak 
Sorry, I cannot really give you any hints.
As far as I know, Facebook WiFi is a closed source captive portal that router vendors can licence to embed in their firmware.
It is not supported by OpenWrt, and is incompatible with openNDS.
In addition, it ignores in numerous ways the CPD security built into most modern devices, so in many cases will not function correctly, if at all.

Facebook do provide an API to provide "login service" and this can be used with an Internet hosted https FAS server, but would be very much NOT recommended.

Facebook has a growing reputation for being perceived as untrustworthy (to the point they have re-named the company).
A business venue that provides WiFi that appears to be linked to Facebook will also be assumed by an increasing number of people to be untrustworthy as well, so is the last thing you should consider.

"Free WiFi" is something that very much attracts customers. Facebook linked WiFi is more likely to scare them away.

**Comment by PeterHanusiak** [comment]
Hi Rob,

Thanks for the info. Let's stay on the technical level.

Do you have any source which talks about this "*Facebook WiFi is a closed
source captive portal that router vendors can licence to embed in their
firmware*"? I am willing to go down this route, however it is very
difficult to find any information about how Facebook Wifi really works. I
believe it should not be a very complicated mechanism for how wifi routers
communicate with this "Facebook captive portal". I am willing to sniff the
network about what is doing with my wifi router with Facebook Wifi, but I
need some hints.
If you could share anything about this topic, it would be very helpful
(even offline, in case there is something sensitive).

thanks
Peter

**Comment by bluewavenet** [comment]
@PeterHanusiak 

> Let's stay on the technical level.

### How Captive Portals Work

All captive portals rely on the de-facto standard built into all client devices to give the "automatic popup" of the login page(s) required for the client to gain access.
This is known as Captive Portal Detection (CPD) and is client device driven where the device operating system probes the network to either determine if free access is available or to trigger the portal popup.
CPD has evolved over numerous years to be a reliable and secure means of triggering the "login" page of captive portals.

A new standard has been proposed in RFC 8910 and RFC 8908. This is known as Captive Portal Identification (CPI) and is driven by the captive portal, eliminating the requirement for the client device to probe the network. CPI is currently somewhat immature and needs time to evolve before it will be available on all client devices. At the time of writing, very few, if any, vendor implementations exist.

See:
https://opennds.readthedocs.io/en/stable/howitworks.html#captive-portal-detection-cpd

Both CPD and CPI implementations on client devices will take into account that there is very little difference between a Captive Portal (CP) and a Man In The Middle (MITM) attack aimed at the client. CPD implementation varies from vendor to vendor, but leads to a set of rules for the development of the portal component of a Captive Portal. This set of rules will maximise the probability that a client CPD will detect a well behaved Portal, rather than a MITM attack.

See:
https://opennds.readthedocs.io/en/stable/customize.html#rules-for-customised-splash-pages

Most CPD implementations follow these rules in one form or another.

### Facebook WiFi Captive Portal

The Facebook WiFi CP was developed circa 2015. Licencing was made available to ISPs and Router manufacturers.
There was an initial take-up by some manufacturers. However the evolution of CPD, along with the popularity of the Facebook App for IoS and Android devices, made the Facebook WiFi CP ineffective on most modern devices, requiring the user to enter an http port 80 URL, something that has become increasingly difficult with the move to https everywhere.

A generic "custom" implementation of a Facebook WiFi CP is possible using the FB authentication API, but this is fraught with difficulties as the API relies heavily on large javascript libraries that are blocked by most implementations of the client CPD for security reasons.
This security blocking can be bypassed by running the required javascript code on a remote https server. This can be quite complex and resource intensive to achieve so most implementations remain closed source for financial reasons.

User expectations, particularly expectations pertaining to privacy are evolving at an increasing pace. Although FB WiFi with Check-in has many business attractions, it is increasingly not what users want or expect.

**Comment by PeterHanusiak** [comment]
> ### Facebook WiFi Captive Portal

Regarding the Facebook WiFi Captive Portal, based on my observation it works pretty straightforward.

First you have to register your router. It is done by simple calling
https://www.facebook.com/wifiauth/config?gw_id=874434179330340

Trick is in **gw_id**, it is unique to the router. However I could not find anywhere how this id is generated. Closest point to investigate it is ASUSwrt Merlin, however the actual code is not there. This is what I found there (fb_wifi tools are unfortunately missing) https://github.com/RMerl/asuswrt-merlin/commit/2ade8289eea4ea86489b02cc0cc638984ac9b95c

Once your router is registered, you can authenticate the wifi user, it happens by this call:

https://www.facebook.com/wifiauth/login/?gw_id=874434179330340&redirect_url=http%3A%2F%2F10.0.0.1%3A5001%2Ffbwifi%2Fauth%3Fref_id%3DbEals02KaHA772y-wL96FfEwSMm0drifsJN-ZNA7BbI&redirect_mac=9dIILJVXPrhZymMMf4jC5fVLXPxBzvvmkZMGUjNaFX4&s=n

It uses **gw_id** (same from registration), then **redirect_url**, which is callback for router (I assume FB will provide some http input) and finally **redirect_mac**, which is checksum of those two params. However I could not figure out how they did it. It is clearly Base64 encoded and checksum is 256 bits, but no idea what. SHA256?

So if anyone would know how to generate gw_id and redirect_mac, it would be almost complete. Any ideas?

**Disclaimer: those ids I picked from google, they are publicly available. Original URL** - https://www.facebook.com/1141557065881995/posts/httpsmfacebookcomwifiauthlogingw_id874434179330340redirect_urlhttp3a2f2f100013a5/1570442122993485/

**Comment by bluewavenet** [comment]
> Regarding the Facebook WiFi Captive Portal, based on my observation it works pretty straightforward.

It is included in proprietary closed source firmware and is straightforward to set up. But as it is very outdated and does not comply with the CPD rules implemented in most mobile operating systems, is very problematic and usually does not work correctly for most clients.

For example the link you provided ( `https://www.facebook.com/wifiauth/login/?gw_id=874434179330340&redirect_url=http%3A%2F%2F10.0.0.1%3A5001%2Ffbwifi%2Fauth%3Fref_id%3DbEals02KaHA772y-wL96FfEwSMm0drifsJN-ZNA7BbI&redirect_mac=9dIILJVXPrhZymMMf4jC5fVLXPxBzvvmkZMGUjNaFX4&s=n` ) does this:

```
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/y7/l/0,cross/g6dSMmpNIH1HFx3QEiEBp4.css?_nc_x=JukhPmZ1xmz" data-bootloader-hash="nuHa9gj" crossorigin="anonymous" data-p=":7,95" data-c="2" />
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yH/r/XJxTSIAjr3c.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yH/r/XJxTSIAjr3c.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="slqBrCn" async="1" crossorigin="anonymous" data-p=":1" data-btmanifest="1004897990_main" onload="_btldr[&quot;slqBrCn&quot;]=1" onerror="_btldr[&quot;slqBrCn&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3igr_4/yH/l/en_GB/Vks0wt6LcUR3_jjBy0Ma-9iIZu6XPLjKZ.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3igr_4/yH/l/en_GB/Vks0wt6LcUR3_jjBy0Ma-9iIZu6XPLjKZ.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="Wusf/fF" async="1" crossorigin="anonymous" data-p=":16,5,25" data-btmanifest="1004897990_main" onload="_btldr[&quot;Wusf\/fF&quot;]=1" onerror="_btldr[&quot;Wusf\/fF&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3i2Gk4/yV/l/en_GB/Sh070k4gS2nO5zZ8rrbXycQTnnN4jNEKwji-K9iyDFjiEKWvu94rOXkYat3x0Antogqxkyu7zSbioteZFeEiP0MXf4ulXpfrLrO2JSlWTP3xHer1KOvuMViQY2-CbtMSAHCS7NJvBeNDHhOy1c9qFAXo-sP2eUmpI9baaYRGz6nSQywGvfJXYOt-cuA3hGONJao42fRpJIFkR3OppvuLhhE8dp96Xc-buPNEADHwxalYt46Cl9qo9Y9O-pXoHRoJXUcaSy-SQsxRAcmil1Wi_58fLKOJqN1eVazMN05s77C3sWtskTD9nMkHkfZeeYBwgy7w4nfYt0.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3i2Gk4/yV/l/en_GB/Sh070k4gS2nO5zZ8rrbXycQTnnN4jNEKwji-K9iyDFjiEKWvu94rOXkYat3x0Antogqxkyu7zSbioteZFeEiP0MXf4ulXpfrLrO2JSlWTP3xHer1KOvuMViQY2-CbtMSAHCS7NJvBeNDHhOy1c9qFAXo-sP2eUmpI9baaYRGz6nSQywGvfJXYOt-cuA3hGONJao42fRpJIFkR3OppvuLhhE8dp96Xc-buPNEADHwxalYt46Cl9qo9Y9O-pXoHRoJXUcaSy-SQsxRAcmil1Wi_58fLKOJqN1eVazMN05s77C3sWtskTD9nMkHkfZeeYBwgy7w4nfYt0.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="JqsSSr/" async="1" crossorigin="anonymous" data-p=":14,112,8,70,3,9,62,32,77,2894,64,27,6,54,186,93,50,74,20827,4,15,29,66,2,23,20826,431,531,13,27332" data-btmanifest="1004897990_main,1004897990_longtail" onload="_btldr[&quot;JqsSSr\/&quot;]=1" onerror="_btldr[&quot;JqsSSr\/&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3ihlJ4/yS/l/en_GB/w34XXaXnY_m.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3ihlJ4/yS/l/en_GB/w34XXaXnY_m.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="84zH34z" async="1" crossorigin="anonymous" data-p=":11" data-btmanifest="1004897990_main" onload="_btldr[&quot;84zH34z&quot;]=1" onerror="_btldr[&quot;84zH34z&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/UoqyOAcZr6q.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yK/r/UoqyOAcZr6q.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="TqTM7j+" async="1" crossorigin="anonymous" data-p=":46" data-btmanifest="1004897990_main" onload="_btldr[&quot;TqTM7j+&quot;]=1" onerror="_btldr[&quot;TqTM7j+&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3i1Gx4/yv/l/en_GB/12yrAU1YHWs.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3i1Gx4/yv/l/en_GB/12yrAU1YHWs.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="L0Xaz5L" async="1" crossorigin="anonymous" data-p=":187" data-btmanifest="1004897990_main" onload="_btldr[&quot;L0Xaz5L&quot;]=1" onerror="_btldr[&quot;L0Xaz5L&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3ifmV4/yS/l/en_GB/Ap63TlEJs_2KN71IT5S2MC8rN_lqIrwjCFDyOmHhWm-Flpu4OV0GQeEH-tob5bB7FAUOykRBExEA6OYXqb_kLe0DVA8_XgAh1pEuv-3OyNNCaY3EDP5wDfq53.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3ifmV4/yS/l/en_GB/Ap63TlEJs_2KN71IT5S2MC8rN_lqIrwjCFDyOmHhWm-Flpu4OV0GQeEH-tob5bB7FAUOykRBExEA6OYXqb_kLe0DVA8_XgAh1pEuv-3OyNNCaY3EDP5wDfq53.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="pqrC82a" async="1" crossorigin="anonymous" data-p=":131,47,170,98,45,63,137,82,128,12,59" data-btmanifest="1004897990_main" onload="_btldr[&quot;pqrC82a&quot;]=1" onerror="_btldr[&quot;pqrC82a&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3isly4/yA/l/en_GB/8yoaXsjz3D-.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3isly4/yA/l/en_GB/8yoaXsjz3D-.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="LuLTc0o" async="1" crossorigin="anonymous" data-p=":31" data-btmanifest="1004897990_main" onload="_btldr[&quot;LuLTc0o&quot;]=1" onerror="_btldr[&quot;LuLTc0o&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3iSUg4/yB/l/en_GB/7ab1LboWIaH.js?_nc_x=JukhPmZ1xmz" as="script" crossorigin="anonymous" nonce="1Nl70wBf" /><script src="https://static.xx.fbcdn.net/rsrc.php/v3iSUg4/yB/l/en_GB/7ab1LboWIaH.js?_nc_x=JukhPmZ1xmz" data-bootloader-hash="EQm5Vsq" async="1" crossorigin="anonymous" data-p=":17" data-btmanifest="1004897990_main" onload="_btldr[&quot;EQm5Vsq&quot;]=1" onerror="_btldr[&quot;EQm5Vsq&quot;]=1" nonce="1Nl70wBf"></script>
<link rel="preconnect" href="//scontent.xx.fbcdn.net" /><link rel="dns-prefetch" href="//video.xx.fbcdn.net" /><!--EF-->
```
**All of this will be blocked by most client device CPD implementations.**
Modern clients will most likely see a blank page.
It is implemented on the client in this way for security reasons **_ie to prevent unknown code from being run when connecting to a public wifi._**
Sure, if you try this in the normal browser on your laptop it might work, but then you would be vulnerable to all sorts of MITM attacks.
