### ISSUE TITLE
Can I use Lighttpd while openNDS is running?

### ISSUE THREAD

**Issue by basconesherman** [openNDS/openNDS#299]
Hello. Im just wondering if I can use Lighttpd server while the openNDS is running. 

hardware: Raspberry Pi 3b+
openNDS: v9.5.1

Im using the basic continue function of openNDS not fas. The Lighttpd server is located @ 10.3.141:8080 since Ive read that the port 80 is already occupied by openNDS. Currently Im able to access it when connected on openNDS access point. But when I added images, there is a broken image(the one you are seeing if the browser cant load the image) but there is no 404 error. that's why Im pretty stuck.

When Im loading a textfile and displaying the content, it's working fine. So the directory is working, my only problem is that I cant load images. 

As of now, all default settings of openNDS is working fine.
But I want to customize it even further, as Im reading your documentation, I found out that you cant use upload function on a captive portal. That's why I came up on the idea of using a web application thru lighttpd which will do the uploading function.

The web app is with login option to make sure that the right person is the only one who can access it. 

Im just asking if this is possible so that I can continue and stop wasting my time if its not.
Thank you!

**Comment by basconesherman** [comment]
To add some details

The captive portal will be used on a small coffee shop. We already tested the openNDS on it for about a month now. The maximum concurrent users will be 20 at most. The connection is fine and decent. I did this test run to make sure that theres no problem even when Im just using RPi because you suggested that I must use AP to make it better, but yes the budget of the owner is pretty limited. :) But its working fine. I just needed to add the uploading system.

I just wanted the owners to have an automated uploading system for them to do it on their own while Im not with them. The system is just for changing the images on the splash page.

**Comment by bluewavenet** [comment]
@basconesherman 

> Im just using RPi because you suggested that I must use AP to make it better, but yes the budget of the owner is pretty limited

This does not make sense because a RPi system would be multiple times more expensive than a dedicated router would be.
In addition, the Rpi wifi is NOT designed to be used in AP mode. It will work, as you have found out in your testing, but it is very inferior in that mode, particularly with respect to range and speed.

> as Im reading your documentation, I found out that you cant use upload function on a captive portal

Where does it say that? You must be misunderstanding something.
openNDS has built in support for automated "uploading" of content updates.
See:
https://opennds.readthedocs.io/en/stable/customparams.html#custom-images
and
https://opennds.readthedocs.io/en/stable/customparams.html#custom-files

The standard theme_click-to-continue-custom-placeholders ThemeSpec is a fully functional example where images and text are downloaded from an external web server. The downloads can be scheduled for regular refreshing.
See:
https://opennds.readthedocs.io/en/stable/config.html#set-refresh-interval-for-downloads

**Comment by basconesherman** [comment]
From the part of the documentation saying that you mist avoid using href.

They do not need to buy a router because they already have a RPi from their paid wifi business before. Thats why they insist to use the RPi. 

Okay I will try to dig deeper on that part of the documentation

But back on my original question, can I use lighttpd? So that I will host the web app their?

**Comment by basconesherman** [comment]
In this setup, web app and opennds is completely separated. I will use the web app to upload and delete images from the htdocs of opennds. So that the filename that the opennds will be updated but it always have the same filename.

For example 

The main bg of the splash page is mainbg.jpg

In the web app, the use can upload a mainbg.jpg that will overwrite the current background. 

In this approach, I dont have to change any thing on opennds since it currently loading the mainbg.jpg

I hope you get my point

**Comment by bluewavenet** [comment]
@basconesherman 

> But back on my original question, can I use lighttpd? So that I will host the web app [there]?

Yes. Then configure openNDS to "download" the required content changes from lighttpd. In this case it will be more of an "Import" rather than a "download" of course. openNDS handles all access rights etc etc, putting the imported data where MHD can serve it to clients. (MHD is the web server built into openNDS)

**Comment by basconesherman** [comment]
Nice thats cool! Can you point me how can I configure openNDS with those things you say? At least in your documentation?

**Comment by bluewavenet** [comment]
@basconesherman 

> Can you point me how can I configure openNDS with those things you say? 

I did already....

> openNDS has built in support for automated "uploading" of content updates.
> See:
> https://opennds.readthedocs.io/en/stable/customparams.html#custom-images
> and
> https://opennds.readthedocs.io/en/stable/customparams.html#custom-files
> 
> The standard theme_click-to-continue-custom-placeholders ThemeSpec is a fully functional example where images and text are downloaded from an external web server. The downloads can be scheduled for regular refreshing.
> See:
> https://opennds.readthedocs.io/en/stable/config.html#set-refresh-interval-for-downloads

**Comment by basconesherman** [comment]
Thank you for your assistance. Appreciate it man!
