### ISSUE TITLE
Configuration for offline use.

### ISSUE THREAD

**Issue by samuk** [openNDS/openNDS#337]
It seems that once a year  in spring someone tries to set up a captive portal for offline use and then gives up. Eg [2020](https://github.com/openNDS/openNDS/issues/68), [2021](https://github.com/openNDS/openNDS/issues/170)

This year it's my turn. I'm using Armbian on a Orange Pi Zero with 512MB of Ram, I've documented my [setup here](https://github.com/Agroecology-Lab/edu-hotspot/#readme)

I currently have piratebox set up on it. It's serving an ESSID. There's content on it.

The captive portal stuff is a bit flaky on Piratebox.  My default browser on the Android device is Firefox.

On Android (my target device) when connecting to the hotspot

1) it pops up a system message asking me to login.
2) If I click this it redirects me to the local piratebox webpage piratebox.lan
3) I can see the content, but not interact with it (uploads or downloads don't work)

If I go to 'three dot' menu I can see an option 'use network as is' If I do this the window disappears.

If I then open a Firefox browser I can navigate to piratebox.lan I can then upload/download content.

I can ping piratebox.lan in Termux

If I then open a Chrome browser I cannot navigate to piratebox.lan 

If I type the IP into Chrome I'm redirected to piratebox.lan/content which then works.

Is this as good as it's going to get? The user experience kinda sucks but maybe it will have to do.

Does openNDS offer the possibility of something more seamless?

**Comment by samuk** [comment]
Thanks. I just tested it on windows and it seems to work flawlessly!?

On Debian/ Firefox it gives a popup thing that redirects to the correct page.

Debian/Chrome no popup.

I guess I can just include instructions in the captive portal setup:

1) find a bit of paper or a text editor: write down piratebox.lan/content
2) Click the three dot and 'use network as is'
3) open a browser and visit piratebox.lan/content

**Comment by bluewavenet** [comment]
@samuk 

> Thanks. I just tested it on windows and it seems to work flawlessly!?

Windows doesn't care much about security.....

> On Debian/ Firefox it gives a popup thing that redirects to the correct page.

The built in CPD in Debian is disabled by default (I think). Firefox has its own CPD (enabled by default). On a desktop/laptop it is not much of a security risk if you are choosing to start the browser before getting the splash page sequence. 

> Debian/Chrome no popup.

Chrome has its own CPD just like Firefox has, but it is disabled by default.

**Comment by SergioDG-YCC** [comment]
I know it's been a while, but I guess it can help someone.
I read point 3 above. I can see the content, but not interact with it (uploads or downloads don't work)
The problem is the html layout of your local website. You can fix it by using the local html from opennds/nodogsplash, with an 'iframe' to your local web. Said iframe is displayed in full screen on an android, with the correct css that I leave below:

HTML: splash.html

<head>
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
<meta HTTP-EQUIV="Pragma" CONTENT="no-cache" CHARSET="utf-8">
<meta http-equiv="Expires" content="0" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel='shortcut icon' href='$images/logo.png' type='image/x-icon' />
<link rel="stylesheet" href="splash.css" media="screen">
<body >
<div class="iframe-16-9"><iframe src="path/to/you/index.html" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"></iframe></div>
....

CSS: splash.css

body {
    background-color: #009688;
min-width: 100%;
overflow-x:hidden;
}
.iframe-16-9 {
    position: relative;
    padding-bottom: 177.77%;
    padding-top: 35px;
    height: 0;
    overflow: hidden;
}
.iframe-16-9  iframe {
    position: absolute;
    top:0;
    left: 0;
    width: 100%;
    height: 100%;
}

**Comment by bluewavenet** [comment]
@SergioDG-YCC 

> Said iframe is displayed in full screen on an android

Iframes are blocked on many implementations of CPD so there is no guarantee of consistent results.

**Comment by SergioDG-YCC** [comment]
> @SergioDG-YCC
> 
> > Said iframe is displayed in full screen on an android
> 
> Iframes are blocked on many implementations of CPD so there is no guarantee of consistent results.

I currently use it with no problems. I load an external advertising website, allowed in the configuration file =)

**Comment by SergioDG-YCC** [comment]
The trick is that the remote web is 'responsive'
i forgot to mention it

**Comment by bluewavenet** [comment]
@SergioDG-YCC 

> The trick is that the remote web is 'responsive'

There is no "trick", it will not matter what level of responsiveness is provided by a remote web site, because the built-in "popup" web browser on the client device has its functionality restricted deliberately for security purposes (all current Android and iOS CPD implementations).

The restrictions include, but are not limited to:
1. File download and file upload blocked
2. 3rd party javascript blocked
3. iframes blocked
4. hyperlinks blocked

This is 100% dependent on the vendor CPD implementation and there is nothing a captive portal can do to get round this.
Occasionally in the past, clever hacks have found a way, but these were rapidly blocked with security updates.

It is possible to use a FAS in combination with a suitable walled garden configuration, to provide external web site content on the FAS pages BEFORE authentication.

As the support of the old "splash.html" page was long ago deprecated and removed, I suspect, if you have achieved success, you are using a very old version of openNDS, a specially configured or very old Android OS, or have implemented some FAS/WalledGarden solution as I mentioned above.

After authentication most implementations of CPD will close the "popup" browser window, although the built in CPD of mainstream browser software (Chrome, Firefox etc) can be configured to keep a final post authentication page open, but this cannot be forced on an operating system CPD.
