### ISSUE TITLE
OpenNDS running locally on a RPI

### ISSUE THREAD

**Issue by fabiensabatie** [openNDS/openNDS#347]
Hi @bluewavenet !

I'm running OpenNDS on a raspberry pi, and use a node server as a FAS with fas_secure_enabled level 3. Everything is working properly when I use ngrok to generate an https link to my server running locally. 

My first question : is there any way to use https locally ? I've been playing around with mkcert but the certificates I get are not trusted, when the captive portal pops up a "Unsecure connection" page shows up on my devices. Any idea on how to get it all running without ngrok ? :)

Second question : the opennds instance used on the rpi uses the opennds.conf file, thus the log path (as refered to in fas-aes-https.php is "/run". This folder is owned by root and node wont allow me to create a folder or write in it, so I cannot communicate with opennds's Authmon Daemon and pass in sessionlength or uploadrate values for the client, could we make this path configurable from the  opennds.conf file so I can write in "/home/pi" instead ? :)

Great work on OpenNDS man, keep up the good work !

**Comment by bluewavenet** [comment]
@fabiensabatie 

> My first question : is there any way to use https locally ?

No. It is, by design, impossible to create valid TLS certificates  for a "local" https server.

> I cannot communicate with opennds's Authmon Daemon and pass in sessionlength or uploadrate values for the client,

It is not possible to  communicate with Authmon. Authmon is a NAT traversal daemon. It autonomously **_opens a channel to a remote Internet hosted https server_**, and pulls in data from there. There is no API for you to communicate with it locally.

> This folder is owned by root and node wont allow me to create a folder or write in it,

That is a default Linux multi-user security setting. Allowing write access is a fairly trivial but pointless exercise as it will not fix your actual problem. ie your FAS server **must** be Internet hosted for https. 

> so I can write in "/home/pi" instead ?

You should never do this for something like a log file on a device such as a pi, or any device that uses flash memory for storage.
The log file could be written to thousands of times or more per day depending upon how busy your captive portal venue is. This will quite quickly lead to failure of, in your case, the SD card in the pi.

**Comment by fabiensabatie** [comment]
Thanks for your fast response @bluewavenet  !

> It is not possible to communicate with Authmon. Authmon is a NAT traversal daemon. It autonomously opens a channel to a remote Internet hosted https server, and pulls in data from there. There is no API for you to communicate with it locally.

Alright, I am now serving the content of the logfile with my node server, on https://myserver.com/{sha-256 of gatewayname}/{rhid}

At what address must this file with the rhid and sessiontimeout info be served for opennds to read it ? :)

**Comment by bluewavenet** [comment]
@fabiensabatie 

> Alright, I am now serving the content of the logfile with my node server, on [https://myserver.com/{sha-256](https://myserver.com/%7Bsha-256) of gatewayname}/{rhid}

Do you mean you have moved your node server from the pi to an Internet hosted server?

**Comment by fabiensabatie** [comment]
Yes, i now need authmon to read my sessiontimout and dowloadquotas values :)

**Comment by bluewavenet** [comment]
You will have to replicate what fas-aes-https.php does.

1.  From the FAS validation of the client point of view
Start by reading the file (you can find it in /etc/opennds).
Look at `function authenticate_page()`, line 460, and follow the logic from there.

2. The entry point for Authmon is `function auth_get()`
Authmon does periodic post requests.
