### ISSUE TITLE
@bluewavenet hi, i'm tryin to configure a https Fas and i want to know if there is any way to get rid of the port number in the url

### ISSUE THREAD

**Issue by khaledmouna8** [openNDS/openNDS#351]
@bluewavenet hi, i'm tryin to configure a https Fas and i want to know if there is any way to get rid of the port number in the url

_Originally posted by @khaledmouna8 in https://github.com/openNDS/openNDS/issues/321#issuecomment-1136040186_

**Comment by bluewavenet** [comment]
@khaledmouna8 
When openNDS redirects a client to the remote https FAS, it must add the port number to the url, because that is where the FAS server is. The only theoretical exception to this is the https standard port of 443, where it could be left out - but openNDS adds it anyway.

From your post in #321 :

> yes i'm not using 443 as a port in my case 

As you are not using 443, then the port you are using is an essential part of the url.
