### ISSUE TITLE
Bandwidth limit

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#374]
I have successfully deployed my voucher type hotspot.
I saw on the binauth_log.sh that there is a upload and download rate,
I tried to modify it ang setting an specific limit.
When I tried to speed test, bandwidths still exceeds the bandwidth I am expecting to be its limit.
I am planning to limit my users to have 12mbps each.

At binauth_log.sh
```
upload_rate=12000
download_rate=12000
```

Is it possible to limit bandwidth limit per device using openNDS?

**Comment by bluewavenet** [comment]
@xreyc-developers 

> Is it possible to limit bandwidth limit per device using openNDS?

Yes it is. Note that the upload and download rates are **_rate limiting thresholds_** not absolute rate ceiling values.
This is explained here:
https://opennds.readthedocs.io/en/stable/traffic.html#data-rate-quota-threshold

Clients are allowed to burst at high rates for a short interval of time to give a much improved user experience, for example quickly opening an email inbox, opening a web page etc. However if the client persists in driving at high rates, exceeding the threshold values, then the rate becomes throttled. The overall average rate achievable will converge on the set value.

There are many configuration parameters that can be used to tune this but the default values give generally good results.
Changing these parameters _can result in significant memory consumption_, so depending on the amount of ram in the router, some care is required if changing them.

We should however check if setting rate thresholds actually works from binauth - it is supposed to but I am not sure if it was tested for recent releases....

If you run `ndsctl json`, you will see the set values, if it has worked. 

> I have successfully deployed my voucher type hotspot.

**_If you have not already upgraded openNDS to version 9.8.0, then you should do immediately._**

```
opkg update
opkg install opennds
```

Some very new clients (both ios and android) have implemented CPI such that they poll the RFC8910 URL **_VERY_** rapidly.
In openNDS prior to v9.8.0, this could lead to the built in web server becoming unresponsive or even crashing.
This is fixed in openNDS v9.8.0.

**Comment by xreyc-developers** [comment]
> Yes it is. Note that the upload and download rates are rate limiting thresholds not absolute rate ceiling values.

Now I see.
On the documentation I saw, `opkg install sqm-scripts` but I do not know where the config file is located
that's why I installed `luci-app-sqm` instead. Does this package limits users individually?
Is there a more preferred way to do this?

> If you run ndsctl json, you will see the set values, if it has worked.

I tried to run `ndsctl json` it does show 12000 but the users bandwidth exceeds the bandwidth.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> that's why I installed luci-app-sqm instead. Does this package limits users individually?

**No, sqm-scripts does not limit users individually**. You should remove `sqm-scripts` and `luci-app-sqm` as these are not needed.

> I tried to run ndsctl json it does show 12000

Good, that means rate limiting thresholds are indeed activated by binauth.

> but the users bandwidth exceeds the bandwidth.

**Yes, you should re-read the documentation and what I said:**

> **the upload and download rates are rate limiting thresholds not absolute rate ceiling values.**

> **The overall average rate achievable will converge on the set value.**

If you do a speed test, traffic will "burst" at the maximum possible rate until the moving average transfer rate exceeds the configured rate threshold. At that point, the rate will be throttled until the moving average drops below the configured threshold again, at which point the throttling is removed. (If you want to know more about this sort of thing, read about "bucket filters".)

If you want to see the effects of this, try starting a torrent download, then after 30 minutes or so look at the output of ndsctl json again for the client. You should see the session average tending towards the configured threshold, although it will remain slightly higher than the threshold as long as the torrent is still running.

**Comment by bluewavenet** [comment]
@xreyc-developers 
At 12Mb/s for each client, ~70 clients could drive up to 850Mb/s.

A Mikrotik Rb750 Hex will not come anywhere near being able to work at that rate.
I should cope more or less with around 300Mb/s, so a sensible rate limit threshold would be something like 4000 kb/s, rather than 12000.

**Comment by bluewavenet** [comment]
@xreyc-developers 

**Please not my comment earlier on upgrading openNDS to v9.8.0.**
This is essential.

**Comment by xreyc-developers** [comment]
@bluewavenet 

> No, sqm-scripts does not limit users individually. You should remove sqm-scripts and luci-app-sqm as these are not needed.

This is noted, I'll remove sqm.

> Yes, you should re-read the documentation and what I said

Thanks for this, now I understand what it means.
I'll read more on the documentation and other stuff that I need know.

> At 12Mb/s for each client, ~70 clients could drive up to 850Mb/s.
> A Mikrotik Rb750 Hex will not come anywhere near being able to work at that rate.
> It should cope more or less with around 300Mb/s, so a sensible rate limit threshold would be something like 4000 kb/s, rather than 12000.

I'll just add one more mikrotik for now to handle the process.
Then reduce the rate limit to 9000kb/s.
Our local store here is easy to access in my place.

> Please not my comment earlier on upgrading openNDS to v9.8.0.

I'm planning to re-flash OpenWrt and reinstall latest openNDS tonight  to make the storage clear.

**Comment by xreyc-developers** [comment]
Closing it now.
Thank you
