### ISSUE TITLE
Device default MAC address randomizer.

### ISSUE THREAD

**Issue by xreyc-developers** [openNDS/openNDS#375]
I have been having an issue on device MAC address.
I noticed the some device creates a random MAC address every time it reconnects to the network.
So instructed my users to change their Wi-Fi privacy every time they connect to a new hotspot (AP).

![image](https://user-images.githubusercontent.com/25092979/185805116-22100721-cca4-4a1a-9379-91621eda64bd.png)

![image](https://user-images.githubusercontent.com/25092979/185805109-8a37a9d9-76b3-4edd-829c-04f1705c88e4.png)

I want my users to connect to my Wi-Fi without any setup.
I attempted to plant a uuid on the devices local storage to give each device unique identity,
but it gets cleared out everytime the captive portal is reopened.
Seems like things like localstorage, session storage, indexedDB and cookies are not allowed on captive portal.
Is there any solution this?

**Comment by xreyc-developers** [comment]
I am looking around on internet.
Finally I found a way to know if an specific MAC address is randomized.

If a MAC address second character is a 2, 6, A, or E, then it is a randomized address.
x2-xx-xx-xx-xx-xx
x6-xx-xx-xx-xx-xx
xA-xx-xx-xx-xx-xx
xE-xx-xx-xx-xx-xx

Can you confirm this?
Is this implemented on all of the randomized MAC address?
If so, if I detect that the user is using a randomized MAC address I will block it and require the user to change its privacy setting.

**Comment by sicelo** [comment]
Yes it's true about that pattern

However, I think forcing users to change privacy settings is bad user experience. What issues do you have from MAC randomization?

**Comment by xreyc-developers** [comment]
@sicelo 

I agree.
I have created an application that enables user to subscribe their devices to a specific promo.
One user can have multiple device and subscribe each device to specific promo.
On the authentication server, I am linking the promo to device mac address.
But the big problem is that device changes their mac address every time they connect to the hotspot.
I tried to store uuid to device localstorage/indexedDB/session storage/cookies to make it unique but it gets cleared everytime the captive portal show up. Some device able to retain the value but not all specially on ios device.

Is it possible use device browser (chrome/safari) as the captive portal instead of the default captive portal?

**Comment by bluewavenet** [comment]
@xreyc-developers 
Device vendors are continuously working hard to keep their devices secure. The current CPD process, the upcoming CPI process, and the randomisation of mac addresses, amongst numerous other things are there for security purposes and work continues intensively on the subject.
Sure you might find some hack, or some insecure device setup, but it will almost certainly disappear with the next OTA update to that device.

> I am linking the promo to device mac address.

This is very bad.
You should link to the **_user_**, via some username/password/voucher combination and allow only one connection at a time for the voucher.

That way, a user can subscribe to numerous "promos", one for each device they have.

**Comment by xreyc-developers** [comment]
@bluewavenet

Thanks for this.
I agree to this, I need to follow the standard before my system go big.

The biggest issue I am having right now is that users are cheating just to connect to the hotspot.
They might give their username and password to their friends and authenticate all of their device with that one account,
or they create one account for all of them.
My subscription is per device approach (not per user) that is why I am linking it to mac address.

Anyway, I got a new idea. 😄😄
**It is possible to deauthenticate specific mac address using binauth_log.sh?**
Using this command:
`/usr/bin/ndsctl deauth IP|MAC`

This way, I no longer have to list the device of the user.
I can let them subscribe to multiple promo.
 
On the captive portal, user must login then select which subscription they want to use.
One subscription can only have one concurrent working device.
Every time the user is authenticated, the authentication server will record the new mac address and kick the previous mac address authenticated using this command `/usr/bin/ndsctl deauth IP|MAC` on binauth.

Last question.
Is MAC address randomization on the device a bad thing for the DHCP server since it allocates multiple IP address?
One device uses multiple IP address on the router since it has a different MAC address every time it connect.

**Comment by bluewavenet** [comment]
@xreyc-developers 

> MAC address randomization

As far as I am aware, the randomisation occurs only when a device connects to a **_new_** SSID.
A change can possibly be forced by the user telling the device to "forget" the previously used SSID, and then reconnecting.

I think this is the intended operation of the mac address randomisation in both IoS and Android.

> Is MAC address randomization on the device a bad thing for the DHCP server ...?

Only if you have a very long lease and everyone is telling their devices to "forget".
What lease time do you have? Typically 30 minutes or less is common for a busy captive portal venue.

> My subscription is per device approach

**_This is the core of your problem. You are trying to monetise venue Internet access, whereas the rest of the world abandoned this years ago in favour of FREE WiFi to attract customers to the venue._**

Having said this, to solve your problem, I think you will have to do as you say ie deauth the client device if the user logs in on another device.

I can think of various ways to achieve this:
1. As you say, deauth from binauth_log.sh.
_However you cannot run `ndsctl deauth` from within a binauth script._ This is because ndsctl uses Linux socket access to communicate with openNDS. But the binauth script is run from inside the openNDS thread, so attempting socket access will lead to a deadlock. openNDS uses socket locking to prevent this.
You would have to get binauth_log.sh to write a "deauth database" on /tmp somewhere, then start a background process using the libopennds library to do the the required deauth(s) based on the contents of that deauth database.

2. Use a different approach - Your FAS should only allow use of a "voucher" one time, unless it is signalled somehow that the previous login has been deauthed for whatever reason (eg inactivity timeout, user logout).
Binauth has a list of "methods".
See: https://opennds.readthedocs.io/en/stable/binauth.html#binauth-command-methods
When a deauth method is detected, your binauth script could signal your remote FAS server using the wget command with an appropriate query string. Your FAS would have a new entry point that recognises the deauth signal query string.

I would favour option 2, as it uses the built in api of binauth so will be easier to implement and consume less memory than the first option.

**Comment by xreyc-developers** [comment]
@bluewavenet 

> As far as I am aware, the randomisation occurs only when a device connects to a new SSID.
> A change can possibly be forced by the user telling the device to "forget" the previously used SSID, and then reconnecting.

Yeah it does happen on my case since I have multiple AP.

> Only if you have a very long lease and everyone is telling their devices to "forget".
> What lease time do you have? Typically 30 minutes or less is common for a busy captive portal venue.

Currently working on default lease time.

> This is the core of your problem. You are trying to monetise venue Internet access, whereas the rest of the world abandoned this years ago in favour of FREE WiFi to attract customers to the venue.

I am trying to implement something like this https://www.adopisoft.com/.
I am trying to provide internet in a very cheap cost and the main reason is that many can't afford internet access (this is common in developing countries like mine).
For now I am selling internet for a very cheap price to cover the cost used on building many hotspot tower in many location. Then later turn it into advertising platform with free internet (the user just need to click the advertised page to access internet).
Next plan is a secret for now.

> When a deauth method is detected, your binauth script could signal your remote FAS server using the wget command with an appropriate query string. Your FAS would have a new entry point that recognises the deauth signal query string.

Do you have sample for
```
action=$1
if [ $action = "client_deauth" ]; then
     $2 client mac // users mac
    // WGET COMMAND HERE
fi
```
