### ISSUE TITLE
NDS-started hook?

### ISSUE THREAD

**Issue by afriza** [openNDS/openNDS#402]
I want to modify `iptables` rules after openNDS has started.

It is like `fwhook_enabled` but for me/my-app to get notified if openNDS has started so that I can apply my own `iptables` rules.

Currently, during boot, I have a script that waits for openNDS `iptables` chains to be created and apply my rules.

But if openNDS is restarted, I will need to restart my script.

One approach that I can think is for my script to poll PID of openNDS and if it changes, reapply my rules. But this will be my last resort.

Does adding `nds_start` event/method in `binauth` okay?
Existing events/methods are auth/deauth related as the name `binauth` implies.

---
As a side question, in firewall4 of OpenWrt 22.03, do you have a substitute for `fwhook_enabled`?
Or is some other mechanism in place?

**Comment by bluewavenet** [comment]
@afriza 
From OpenWrt 23.3.1. onwards, firewall "include" options have been reinstated, working exactly as they did in fw3.
The openNDS fwhook script is now functional again when called by a firewall restart.

Similarly you can now run your own script as an include when fw4 starts. openNDS uses iptables-nft, so your additional firewall rules can be iptables calls. The config needs to be "type script" and point to an executable script. See the firewall config entries that openNDS adds.

For fw4 rules to apply to openNDS clients, all openNDS rules set in its config should be "passthrough" rather than "accept". Passthrough is the default for unspecified "default rules".

Binauth is only called when a client is authenticated or deauthenticated - on a client by client basis, so probably not applicable for what you are trying to do.

Finally, for your information, openNDS v9.9.0 introduced the heartbeat file.
it is useful for checking if openNDS is running and alive.
See:
https://opennds.readthedocs.io/en/stable/customize.html#the-heartbeat-file

**Comment by afriza** [comment]
I haven't checked openNDS docs & implementation;

If I want to exclude some traffics of preauth & auth'ed users from data usage, are accept & passthrough rules sufficient?

**Comment by bluewavenet** [comment]
@afriza 

> I haven't checked openNDS docs 

A bit lazy.... ;-)

By default preauthed clients are blocked from everything.
By default authed users have no restrictions.
For authed users:
https://opennds.readthedocs.io/en/stable/config.html#access-control-for-authenticated-users

If you want to block CDNs (eg Facebook), you will have to use passthrough and define your own ipsets in the OpenWrt firewall.

**Comment by afriza** [comment]
> A bit lazy.... ;-)

Hahaha.. Actually I wanted to check, but other urgent tasks came and I want to post something before this issue gets closed..

Back to the [main question](https://github.com/openNDS/openNDS/issues/402#issuecomment-1306533770), I cannot find the answer in [the link](https://opennds.readthedocs.io/en/stable/config.html#access-control-for-authenticated-users) you gave.

For auth'ed clients, I assume both `allow` and `passthrough` traffics are still counted towards data usage?

So is there a way to exclude some traffic from data usage?

What I mean is, for free-sites, clients can use as many data without reducing (or counted towards) their volume-quota.

My guess is that traffic to `walledgarden` IPs doesn't count?
But I need to omit the ports to allow `udp` and this ends up allowing **_all traffics_** for `walledgarden` IPs?

**Comment by bluewavenet** [comment]
@afriza 

> Back to the main question, I cannot find the answer in the link you gave.

If you want additional rules to be applied to clients, then as long as you use passthrough, these rules can be placed in the OpenWrt Firewall.

> So is there a way to exclude some traffic from data usage (volume-quota)?

No. The volume quota is the volume of data your isp is being paid to transport, regardless of protocol. 

> What I mean is, for free-protocols to free-sites (identified by tcp/udp IP-port)

I have never heard of "free-protocols". ISPs don't care either. Traffic is traffic. Volume quotas are quotas of traffic.

> My guess is that traffic to walledgarden IPs doesn't count?

Walled garden traffic applies only to preauthenticated clients, so does not count towards an authenticated clients traffic.

> allow udp

So you want preauthenticated clients to be used for gaming or torrenting? Do I detect a hint of untrustworthiness or dishonesty in your application?
