### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by tvogel** [openNDS/openNDS#408]
Hi! Are there any plans yet to make this work with IPv6 enabled? (i.e. to capture IPv6 connections, too, or at least to prevent IPv6 sneaking past in unauthenticated state)

**Comment by bluewavenet** [comment]
@tvogel 
It is not really a matter of planning to add support. Currently the universally accepted standard for Captive Portal Detection (CPD) and the associated DNAT redirect makes it somewhat tied in to IPv4 without resorting to horrendous hacks.
The new standard CPI method (rfc8910/rfc8908) will fix the problem, but this is not yet widely supported or even mature enough for reliable use with most devices. New releases of client operating systems are slowly beginning to appear with at least some sort of support, but it is going to take some time for it to become a widely supported standard.

The easiest way forward for now is to disable IPv6 support on the Captive Portal lan.
In practice, the vast majority of ISPs do not, by default, provide IPv6, although this is slowly changing, so for most people it is not yet an issue.

**Comment by tiagogaspar8** [comment]
Hi @bluewavenet!

Can we reopen this? Even just for tracking purposes?

We are seeing an increased Ipv6 adoption and as you mentioned OpenNDS already supports CPI rfc8910/rfc8908, so now it makes sense to think about this?

I'd love to have IPv6 support for this!

Thanks!

**Comment by bluewavenet** [comment]
@tiagogaspar8 
Rather than reopening this, a new issue should be opened, for both discussion and community tracking.
See this issue:
https://github.com/openNDS/openNDS/issues/623#issuecomment-2351170959

This shows that only now, 2 years later, has anyone encountered a problem.
The adoption of ipv6 is very likely to be at the very beginning of an "exponential" S curve.

>  so now it makes sense to think about this?

Indeed it does ;-)

I will create a new pinned issue and link it here.....

**Comment by tiagogaspar8** [comment]
Awesome, thanks for this!
