### ISSUE TITLE
Only use FAS domain name instead of fasremoteip

### ISSUE THREAD

**Issue by bluepuma77** [openNDS/openNDS#421]
Thanks for providing openNDS, just working my way through the docs, tutorials and first implementation. 

One thing that bothers me is the fixed IP used for FAS `fasremoteip`. If we do a large rollout and the IP changes for whatever reason, every device would need to be updated. Is there no way to just use a domain name and do an IP lookup at the moment of use?

Part of the lookup logic is probably already implemented for the "Autonomous Walled Garden".

**Comment by bluewavenet** [comment]
@bluepuma77 

> One thing that bothers me is the fixed IP used for FAS fasremoteip

The issue here is that access to the remote FAS must be granted to preauthenticated clients and this can only be done by ip address.

For a remote FAS, two scenarios to consider are:
1. Single Venue, Single FAS
Here, the remote FAS is accessed by a single openNDS instance.
This is most commonly used by venue operators doing their own development.
The remote FAS could be hosted on any type of web service, the cheapest being a standard "shared hosting" service with a single ip address, but could be any type.
The ip address used for `fasremoteip` must point to the hosting server, but `fasremotefqdn` must also be specified to allow the hosting service to identify which "web site" to serve.
https://opennds.readthedocs.io/en/stable/config.html#set-fasremotefqdn
(If the hosting is on a CDN, it is more complex and walled garden configuration is required.)

2. Multi venue, single FAS
Here, the remote FAS can be accessed by an unlimited number of openNDS instances, subject only to hosting service traffic constraints.
This is most commonly used by Captive Portal Providers.
The remote FAS can be hosted on any type of web service and all requirements are the same as for single venue.
OpenNDS informs the FAS of its identity so the served login sequence can be customised for each instance of openNDS if required.

In both scenarios, if the `fasremoteip` changes, the openNDS config must be updated somehow.
An ip change will be rare, but can happen. For a single venue, it is not much of a problem, but as you say, for multiple venues, if could be an issue.

Automating this is usually the responsibility of the Captive Portal Provider's remote management and is outside the scope of what openNDS does.

That said, it should be possible to periodically check the resolved ip address of fasremotefqdn, but for a CDN this may give a different ip address every time. Usually, at boot time, when openNDS starts the Internet feed cannot be guaranteed to be established so this cannot be done at startup. So as you can see, it is not a simple matter.

A possible solution is for openNDS to use the `walledgarden` ipset instead of `fasremoteip`, but the additional dependencies must be installed and `fasremotefqdn` must be included in the set - more complexity and, up to now at least, regarded as unnecessary bloat to the openNDS code.
