### ISSUE TITLE
Configuring openNDS to work on two devices 

### ISSUE THREAD

**Issue by d1stox** [openNDS/openNDS#434]
hello, currently I am trying to implement a captive portal that works on two bridge devices simultaneously :  br-wlan and br-lan.2 (vlan that works on port lan2) . I modified the "gatewayinterface" but it doesn't seem to work . is there any way to do this ?

**Comment by bluewavenet** [comment]
@d1stox 

> is there any way to do this ?

**No**.
It is intentionally excluded as a configuration option. If you have a requirement for a different portal splash page sequence for multiple network segments, then I would strongly argue that the requirement has been badly interpreted.
The implication is that you would want an independent portal for each subnet and that is best done by having a local instance of openNDS for each subnet rather than having multiple concurrent portal configurations on a single router.
