### ISSUE TITLE
Creating a Custom Captive Portal

### ISSUE THREAD

**Issue by liamvrog** [openNDS/openNDS#472]
Please advise. I installed OpenWRT 19.07.5 and opennds 5.2.0-1 on Keenetic 4G (KN-1211). Problem: They asked for help in creating a Captive Portal with the following requirements, a receipt is printed in a cafe when buying coffee, the receipt has a number that is entered into the database, you can use this number to get an account in the Captiv Portal. I implemented the authentication page with the connected database using Flask in Python. Can I configure Opendns so that it redirects new users to this page, where they must enter this receipt number and other related information internet access is provided.

**Comment by bluewavenet** [comment]
@liamvrog 

> OpenWRT 19.07.5 and opennds 5.2.0-1

These are very outdated and for a long time have not been supported.

> Keenetic 4G (KN-1211)

It seems like this is not supported by official OpenWrt and it only has 32MB flash and 64MB of ram and might be problematic with later versions of OpenWrt anyway.

I would suggest you obtain a more modern OpenWrt supported router.

For your information, there is a community supported ThemeSpec for openNDS version 9.0.0 or greater that implements a voucher system without needing a separate Flask or Python system.
You can find details here:
https://github.com/openNDS/openNDS/tree/master/community/themespec/theme_voucher

**Comment by liamvrog** [comment]
Thanks for the advice. But I really want to try it with OpenNDS. I managed to install everything, run the basic setup and it works. Once it even turned out to make a transfer to my site, but I messed up the configuration file, I had to reinstall everything again. Can you tell me that what I have in mind is implementable using the OpenNDS package? I would like to find out what data should be written in the configuration file for forwarding to my site, and what my site should send to OpenNDS so that he understands that the authentication has been completed.

**Comment by liamvrog** [comment]
Thanks for the advice. But I really want to try it with OpenNDS. I managed to install everything, run the basic setup and it works. Once it even turned out to make a transfer to my site, but I messed up the configuration file, I had to reinstall everything again. Can you tell me that what I have in mind is implementable using the OpenNDS package? I would like to find out what data should be written in the configuration file for forwarding to my site, and what my site should send to OpenNDS so that he understands that the authentication has been completed.

**Comment by bluewavenet** [comment]
@liamvrog 

> Can you tell me that what I have in mind is implementable using the OpenNDS package? 

Yes it is. BUT with your current hardware and OpenWrt version it is very likely to be problematic or maybe not work at all due to resource limitations on your hardware.

**Also openNDS v5 is so very old it is unsupportable.**
For your information the upcoming new release is **version 10.1.0**, and it _**requires**_ OpenWrt version 22.03.x or higher.

If you want to try to make it work you can read the documentation for FAS, but we will not be able to give you much in the way of official support:
https://opennds.readthedocs.io/en/v5.1.0/fas.html#forwarding-authentication-service-fas

**Comment by liamvrog** [comment]
I basically started to get it. That's just the problem with the virtual URL.
I get this from the router:
GET /?authaction=http://192.168.1.1:5000/opennds_auth/?clientip=192.168.1.184&gatewayname=OpenWrt%20openNDS&tok=2aed4a9b&redir=http://192.168.1.1/cgi-bin/luci/

For option fas_secure_enabled '0' should I send such a string?
'http://192.168.1.1:5000 /?tok=9fc0ee82&redir=https://www.google.com'

**Comment by bluewavenet** [comment]
@liamvrog 

> For option fas_secure_enabled '0' should I send such a string?

Level 0 has been deprecated for years now so I do not recall and would have to delve into ancient code to find out....

> If everything works out

I don't think you can sensibly test using the old hardware/opennds.

You can look at the example php files, fas-hid.php for example, designed for level 1, running as a remote FAS.
You would have to translate the relevant bits of code into Python - fairly easy - some people have done this.
Python is not supported in the example scripts because it is not usually available in normal web hosting solutions, it is usually only found in dedicated servers or VPS solutions.
