### ISSUE TITLE
OpenNDS: stop blocking access to LuCI

### ISSUE THREAD

**Issue by diogohvo** [openNDS/openNDS#487]
How can I make openNDS stop blocking access to LuCi gui?

I am running openwrt 22.03, opennds 10.1.0
I have a wifi interface  subnet 192.168.2.0, and this is where opennds is listening. LAN interface subnet is 192.168.1.0, and this interface ip is 192.168.1.1, which is where i access luci.

**Comment by bluewavenet** [comment]
@diogohvo 
Since OpenWrt 21.02, Luci should be accessed via https although access via http was also possible but deprecated.
However port 80 ( the common port for http) is reserved for CPD/CPI on a captive portal and therefore redirects to openNDS.

In your case, go to https://192.168.1.1 and accept the self signed certificate to log in to Luci.

**Comment by diogohvo** [comment]
It indeed works, thank you very much! Can I ask another question regarding opennds or should I open a new thread?

**Comment by bluewavenet** [comment]
@diogohvo 
If it is a new subject, please open a new issue.
