### ISSUE TITLE
change log_mountpoint to /mnt/sda1

### ISSUE THREAD

**Issue by moukir-link** [openNDS/openNDS#500]
hi developers please help.i installed openNDS in openwrt router and everything work perfectly,but after reboot i lose the file vouchers.txt that located in /tmp.
my question is how can i change the logdir from tmpfs /tmp to my USB drive /mnt/sda1
note: i read the opennds documentation and i didn't understand where i have to change this (log_mountpoint '/logs')

**Comment by bluewavenet** [comment]
@moukir-link 
The relevant documentation is here:
https://opennds.readthedocs.io/en/stable/config.html#local-log-mountpoint

This refers to a configuration option in openNDS.

I assume you are using this:
https://github.com/openNDS/openNDS/tree/master/community/themespec/theme_voucher

If so, you have already added some configuration options to openNDS.

If you do not understand OpenWrt configuration, before continuing with this project, you really need to do some background reading, rather than blindly follow a user guide.

Hint: You can either edit the config file directly, or you can use the uci command line utility (as you have already done to get the theme_voucher working).

**Comment by moukir-link** [comment]
thank you Sir for your reply.
i'm using openwrt for a years and i know how to change conf using CLI or UI that's not my problem Sir.
my problem is which file i have to edit?theme_voucher?
![Uploading Screenshot_20230820-105905.png…]()

**Comment by bluewavenet** [comment]
@moukir-link 
The title of this issue is "change log_mountpoint to /mnt/sda1"

That is an openNDS config option.

However if you want to change the location of the voucher database then see:
https://github.com/openNDS/openNDS/blob/master/community/themespec/theme_voucher/theme_voucher.sh#L490

See also #300 

As this is a community themespec script it might be worth asking the author @fservida

**Comment by moukir-link** [comment]
i have read all this issues but still not understand.
![Uploading Screenshot_20230820-115406.png…]()
![Uploading Screenshot_20230820-115610.png…]()

**Comment by moukir-link** [comment]
just tell me which file in openNDS files i have to edit.
that's my question

**Comment by fservida** [comment]
https://github.com/openNDS/openNDS/blob/1a39b43298958a954447850941e2e20b1d9f6dda/community/themespec/theme_voucher/theme_voucher.sh#L98C34-L98C38

The voucher file is to be stored in nds default directory.
If you want to change that just edit the line above to match the location of your file.

**Comment by moukir-link** [comment]
> https://github.com/openNDS/openNDS/blob/1a39b43298958a954447850941e2e20b1d9f6dda/community/themespec/theme_voucher/theme_voucher.sh#L98
> 
> The voucher file is to be stored in nds default log directory. If you want to change that just edit the line above to match the location of your file.

thank you so much.i will try it and i will post the result here

**Comment by moukir-link** [comment]
> https://github.com/openNDS/openNDS/blob/1a39b43298958a954447850941e2e20b1d9f6dda/community/themespec/theme_voucher/theme_voucher.sh#L98
> 
> The voucher file is to be stored in nds default log directory. If you want to change that just edit the line above to match the location of your file.

thank you very much Sir it works perfectly.i asked this question in several platforms and no answer.
![voucher roll](https://github.com/openNDS/openNDS/assets/116383312/c8dea87a-b8da-46b3-86d7-9d88206df294)
