### ISSUE TITLE
install fas aes php on remote server

### ISSUE THREAD

**Issue by daler-api** [openNDS/openNDS#512]
Hi all. I have been working for the third day without a break, but I did not manage to install fas-aes.php on my server. Please someone explain python to a developer who apparently doesn't know how to read documentation on how I can install this from start to finish. I would be extremely grateful for any help!!

**Comment by bluewavenet** [comment]
@daler-api 

> Please someone explain python

Someone might do that for you but it will not help much here because fas-aes.php is written in PHP.

Installing fas-aes.php on your server is just a matter of copying the file into the web root of the server, assuming the web server is set up to support PHP, as all are or can be.

FYI, here is the relevant documentation:
https://opennds.readthedocs.io/en/stable/fas.html#example-script-file-fas-aes-php

If you need any further help, you will have to provide some information.
ie:
1. Your router hardware details
2. The operating system and its version that you are running on your router
3. The version of openNDS
4. The location of your FAS server (eg Internet, local network, the router)
5. If you installed it yourself, details of the web server you are using.

**Comment by daler-api** [comment]
@bluewavenet 
Hello. Thanks a lot for your answer and your time. Now I'm facing another problem. On my ubuntu Ubuntu 22.04.2 LTS server I successfully installed opennds 10.1.3 but it won't start for me. 
![image_2023-09-07_16-42-07](https://github.com/openNDS/openNDS/assets/57620411/90fe6f94-9a3e-4259-bf60-5c3aa9a61a37)

**Comment by daler-api** [comment]
I did everything as indicated in the documentation. And I'm sure it will start working if opennds starts, what do you think?

**Comment by bluewavenet** [comment]
@daler-api 
`Could not get IP address information of br-lan`

What ip subnet did you define for br-lan?
Or did you not create the lan bridge?

> a developer who apparently doesn't know how to read documentation

Sorry, I could not help myself LOL.
We all have to start somewhere and jumping in here is a good way to learn ;-)

You need to define an interface for the openNDS managed network, ..... or use a default lan interface.

See:
https://opennds.readthedocs.io/en/stable/config.html?highlight=br-lan#set-the-gatewayinterface

**Comment by daler-api** [comment]
@bluewavenet Hello again. You have a way to literally save my life. I figured out the fas and now I need to direct the person to the login page and show him a video that is taken from a third-party resource. Tell me how is this possible?

**Comment by daler-api** [comment]
This must be done not when redirecting, but precisely when entering wifi. I tried to do it via remote FAS but it didn't work. Pages gives cors error when loading video
![image](https://github.com/openNDS/openNDS/assets/57620411/d663bfb8-8ffc-4b22-9de2-0aea38e9f3c1)

**Comment by bluewavenet** [comment]
@daler-api 

> Tell me how is this possible?

It's not. Most devices use a special cut down browser as part of CPD and it certainly will not play a video.
