### ISSUE TITLE
Use tc instead of nftables limit feature

### ISSUE THREAD

**Issue by pozzo-balbi** [openNDS/openNDS#524]
Hi,
I know there is a long thread https://github.com/openNDS/openNDS/issues/259 explaining why the choice fell on the limit feature of iptables/nftables. I am no technical expert, but my understanding was that tc will start delaying the flow of packets once it reaches the limit while iptables/nftables limit feature will simply drop the packets. Hence in the case of tc, the application can recognize the delay and adjust the data transmission speed, a feature of the tcp/ip protocol. With the limit feature, the packets are dropped, and the application will start retransmitting after hitting a timeout.

I hope to understood correctly, that this explains the better userexperience of tc over the limit feature of iptables/nftables. If this is the case, enabling tc as additional feature, would be highly appreciated.

BR

**Comment by bluewavenet** [comment]
@pozzo-balbi 

> in the case of tc, the application can recognize the delay and adjust the data transmission speed

Both tc and nftables limiting both work in very similar ways. Both use Linux kernel features to implement bucket filter rate limiting.
Consider that a data channel/medium will typically have a fixed clock rate. This means that to "slow down" transmission, data must be buffered as required and released for transmission such that an apparent rate is achieved.

In both cases, it is the bucket filter that will do the buffering.

If high data flow rate is sustained, a point will be reached where all buckets are full and an overflow occurs. The overflow consists of dropped packets, regardless of whether tc or nftables-limiting is used.

**The tc module is optimised to hard limit a ceiling rate which will not be exceeded** - dropping packets as required once the bucket filter overflows.

**The openNDS rate limiting using nftables is optimised to trigger rate limiting when a threshold is reached.** A sustained data stream will then begin to fill the bucket filter, again dropping packets as required once the bucket filter overflows.

> that this explains the better userexperience of tc

On what basis are you making this statement?

> With the limit feature, the packets are dropped, and the application will start retransmitting after hitting a timeout.

This is not true, unless you have grossly misconfigured openNDS. A very early implementation did have a bug that could result in this, but that was fixed very soon after it was discovered, some considerable time ago.

The openNDS rate limiting is now quite mature and very flexible.

A typical user at a public wifi venue will have very bursty traffic. For example reading and writing emails, browsing web sites, accessing social media, and somewhat less less likely, streaming audio and or video.

Every venue will have a maximum data rate for its Internet feed so this has to be distributed fairly between users, yet still maintain the best user experience for email, web browsing and social media, yet still allow some streaming.

The openNDS implementation is optimised for this type of operation, rather than simplistically providing a hard ceiling per user.

Rate limiting is dynamically adjusted per user and there are numerous options available to tune performance depending on router resources, Internet feed, number of users etc.

openNDS achieves all this without any additional dependencies.

See:
https://opennds.readthedocs.io/en/stable/traffic.html#data-rate-quota-threshold

If you are seeing a "poor user experience", then we can look closely at your configuration, taking into account the router hardware, number of users and Internet feed rates.

**Comment by pozzo-balbi** [comment]
> On what basis are you making this statement?

In the past I had a limited 4G internet connection. I didn't want to waste it with watching videos at 6 MBps and beyond, so I wanted to limit the speed to 0.5 MBps. That is still a usable internet for surfing, email and watching videos in low res. First I tried iptables with limit feature. A catastrophe. I read further, that for this one needs "tc". Without going further, I just used Gargoyle router software on a 4/32 Wi-Fi Access Point with extra VLAN on the one LAN port to have a limited speed internet at 0.5 MBps. 
Now I setup Wifi here and for simplicity I also wanted to leave a free 0.5 MBps internet for the non-paying guest. Enough to check WhatsApp, make a VoIP call, etc. The Internet here is a 500MBps fiber with average use of 20 MBps and peak usage of 120 MBps. So yes, speed isn't an issue and throttling the internet would not make it faster for the paying guest. So you may ask, why want to limit the speed in the first place...

Let's leave that question open.

Seriously, even with tweaking the settings, you will never get close to a smooth 0.5 MBps that any Gargoyle router software can give you. If you say, that this is not the "use case" you have in mind, I understand and respect. OpenNDS is still a very fine peace of software and thanks for that.

Regarding limit feature of nftables, I assume it works like limit of iptables, which only drops too many packets. Yes, OpenNDS dynamically adjusts the limit rate, but it does not have the "delay" function of tc. Please compare the dropped packets rate of a 0.5 MBps limiting between tc and limit without bursting of nftables...

> If you are seeing a "poor user experience", then we can look closely at your configuration

Thanks for the offer, but as technically explained, you will not be able to mimic even close the gargoyle router experience. And a "bursty" internet is not what I want. For the moment I completely disabled the rate limiting feature., As it does not work at that rate with the intention I had in mind, of giving a slow but perfectly usable internet for free and still have an incentive for the paying guests. 
I also tried a "bursty" internet at 10MBps. Speed wise I did not notice any difference between the case of not using any rate limiting... Hence no rate limiting at the moment...

**Comment by bluewavenet** [comment]
@pozzo-balbi 

>  limit without bursting of nftables...

As I explained earlier, this is NOT how openNDS works by default.

> With the limit feature, the packets are dropped, 

Packets are dropped once the bucket filter overflows. This is a function of the Linux Kernel and is exactly the same functionality that TC uses.

> and the application will start retransmitting after hitting a timeout.

There is no such timeout. Transmitting is never stopped, it is all directed into the bucket filter by nftables in exactly the same way TC does.

As mentioned earlier, an early implementation in openNDS had a bug that produced such an effect, but this has long since been fixed. Perhaps this is was the version you had the bad experience with.....

> you will not be able to mimic even close the gargoyle router experience.

If it is using TC, **it will be hard limiting the upper data rate** by dropping packets that overflow the bucket filter.
The user has a smooth experience precisely because the user traffic profile is bursty. 

openNDS, instead of setting a hard limit, sets a threshold, above which data is passed to the bucket filter. The typical user's bursty traffic will be unrestricted until it reaches the threshold. Short term rates can significantly exceed the set threshold, perfect for rapidly getting your emails or browsing  etc. Sustained traffic however, will, depending on the speed of the Internet feed, progressively fill the bucket filter until packets are dropped. In the case of sustained traffic, the average achieved rate will converge on the configured threshold value.
For example, a torrenting client will see an effectively hard ceiling as if it was being limited by TC.

openNDS allows rates to be set per client, for example a subscribing guest could have a higher rate than a non-subscribing guest. 

openNDS rate quotas do not require any additional dependencies.

If you only want the same set hard limit for all users, you can simply install sqm scripts, or as you have done, install a separate Gargoyle server. or something similar.

> I also tried a "bursty" internet at 10MBps.

You do understand the burstyness is a function of the user's data usage profile and nothing to do with openNDS or TC?

> at 10MBps. Speed wise I did not notice any difference between the case of not using any rate limiting... 

As a typical user profile will average at at least an order of magnitude less than that, then you would not see any difference.
