### ISSUE TITLE
Allowing access to DNS server

### ISSUE THREAD

**Issue by snothub** [openNDS/openNDS#535]
I'm trying to run openNDS on my main router, but DNS is running on another box with different IP. I see now that once I connect to the NDS interface, I have no access to that IP on port 53, so nothing works.

How can I allow access in config? Only thing I've found was `users_to_router`, but as mentioned, this isn't on router.

**Comment by bluewavenet** [comment]
@snothub 
You must set the router dhcp to make the clients use dns on the router.

In this way, a client will request dns from dnsmasq on the router where in turn the router will pass the request to your other box.

This is the only way to do this and it is intentional for security reasons ie clients must do everything through openNDS.

**Comment by snothub** [comment]
Got it, thanks for clarifying.

søn. 22. okt. 2023, 22:01 skrev Rob White ***@***.***>:
