### ISSUE TITLE
Trusted MAC devices route to wrong interface with PBR installed

### ISSUE THREAD

**Issue by JoeDat** [openNDS/openNDS#536]
On my OpenWRT router, I have a Guest interface/network/vlan managed by OpenNDS.  On the same router, I have [PBR](https://docs.openwrt.melmac.net/pbr/) installed.  PBR is configured with my WAN interface as default,  a Wireguard client interface available for policy rules, and a single rule to route a specific CIDR range to the WG interface.  The CIDR range does not include my Guest network.

When PBR is enabled, devices in my OpenNDS Trusted MAC list are routed to the Wireguard interface.  Only these devices in this list are impacted.  Authenticated clients are not impacted.  The problem exists if I disable my single PBR rule and simply leave the WAN and Wireguard interfaces managed, so I know it's not the rule itself.

I've worked around this by creating a higher PBR rule to route Guest network traffic to the WAN interface. But, I'm curious if this is a conflict that can be solved without a workaround rule in PBR, and not sure if this should be solved there or in OpenNDS.  I'm unsure when this issue started since I don't use the Trusted MAC list often.  

I suspect the issue is related to how both PBR and OpenNDS are using packet marking.  I'm seeing the same values for packet marking being used both by the Trusted MAC rules, and PBR.  I can see a recent change was made to openNDS to convert the Trusted MAC list to nftables, so perhaps that's related.  Unfortunately, I don't know enough about how nftables work, so I could be way off!  Let me know what I can provide to help troubleshoot.  

OpenWRT 22.03.3
pbr 1.1.1
openNDS 10.1.3

**Comment by bluewavenet** [comment]
@JoeDat 
Wow, a very complex setup ;-) Nice to hear about it.

>  I can see a recent change was made to openNDS to convert the Trusted MAC list to nftables

Not just Trusted Mac. From v10 onwards, openNDS is fully migrated to nftables, even on OpenWrt 22.03.x.

I have until now, no knowledge of the PBR package, so I followed your link.

> I suspect the issue is related to how both PBR and OpenNDS are using packet marking.

Yes, they clash. 
openNDS uses:
1. 0x30000 for authenticated allowed packets
2. 0x30001 for authenticated blocked packets
3. 0x20000 for trusted packets
4. 0x10000 used internally

Either openNDS or PBR allow the default packet marking to be changed, so we can try a quick config change to see if the issue is fixed.

**_However_**, from the link to the PBR documentation, it seems PBR not only sets an fw_mark, but masks it as well.

**_In PBR's advanced configuration under Luci I see:_**
`wan table fw_mark ` default as 010000 (I assume this is hex)
and
`service fw_mask` default as ff0000 (yup, it's hex)

This probably means if some other package uses an fw_mark of 0x030001, then once masked, PBR will see it as 0x30000

If this is really what happens then PBR can cause even more problems.... 

**As a quick test** try changing the PBR settings as follows:
 
`wan table fw_mark 000100`
and
`service fw mask 00ff00`

**Comment by JoeDat** [comment]
Appreciate the info and background.  I learned some things ;-)

I removed the workaround rule and made the modifications above.  Sure enough, it's working.   I can certainly live with this as a fix instead of a quick test.  Understand that you obviously come from the openNDS perspective, so would you recommend the change should actually be with my openNDS config instead?  To me, seems like it's six of one, half-dozen of the other.  But, maybe there's more to this than I realize.

**Comment by bluewavenet** [comment]
@JoeDat 

> But, maybe there's more to this than I realize.

It depends on what PBR does with its `service fw mask` setting, that is why I suggested changing PBR rather than openNDS, in my view the safest "test".... Without _detailed_ testing and/or checking PBR code I do not know the answer.

**Comment by JoeDat** [comment]
> Without detailed testing and/or checking PBR code I do not know the answer.

That's certainly fair.  As of now, my PBR WG routing rule is working and Trusted MACs are routing properly.  As you mentioned, I can change the openNDS packet marking default as documented [here](https://opennds.readthedocs.io/en/stable/config.html?highlight=packet#packet-marking-compatibility).  I'll play around to see what approach makes the most sense for me.  

I'm good with closing this out.  Thanks for the support!

**Comment by bluewavenet** [comment]
@JoeDat 
FYI: The upcoming v10.2.0 release of openNDS will have a `premptivemac` option. This will work in a similar way to Trustedmac but will be subject to accounting and quotas. This means, for example, an IoT device can be rate limited or subject to the new "fair usage policy" config, also coming in the new release.
