### ISSUE TITLE
Default browser for OpenNDS

### ISSUE THREAD

**Issue by cormacstrain** [openNDS/openNDS#568]
Hi

I had logged a previous issue but Ive found where the actual issue lies (i think)

When logging in through OpenNDS, the site Im am trying to access doesnt work properly under the default browser opened by OpenNDS.  Im using the latest Opennds with the latest Openwrt and testing on an iphone.

So when I log in via OpenNDS the page doesnt function properly, but it does function properly if I open Chrome and go to the same address - whilst still  accessing the web through OpenNDS.

Is there a way i can force OpenNDS to use Chrome rather than the default browser it opens with - or is that defined by the phones default browser?

Thanks

Cormac

**Comment by bluewavenet** [comment]
@cormacstrain 
All user device operating systems have a built in functionality to detect captive portals. This is known as "CPD", or Captive Portal Detection. The client device opens a specially restricted browser for logging in to the captive portal only.

**Comment by cormacstrain** [comment]
is there any way around that that you know of?

**Comment by bluewavenet** [comment]
@cormacstrain 

> is there any way around that

No.
If anyone finds a way then the vendors (ie Apple and Google) will very quickly jump in and fix it as it will be regarded as a severe security issue. This is because it would be a pure man-in-the-middle vulnerability allowing users to be redirected anywhere whilst thinking they were going somewhere else.

**Comment by cormacstrain** [comment]
ok - thanks for the help Rob. very appreciated!
