### ISSUE TITLE
ndscltl using wrong socket name

### ISSUE THREAD

**Issue by pierrejoye** [openNDS/openNDS#573]
Device: [OpenWrt 23.05.2 (r23630-842932a63d)](https://openwrt.org/)
Opennds: opkg opennds - 10.2.0-1 

the socket is /tmp/ndsctl.sock

https://github.com/openNDS/openNDS/blob/99b95176cc26e49a4c092381fe1d04a3e2a1e27d/src/ndsctl.c#L483

Call the config util like:
```
root@OpenWrt:~# /usr/lib/opennds/libopennds.sh get_option_from_config ndsctlsocket
root@OpenWrt:~#
```
returns nothing. and ndsctl failed here:
https://github.com/openNDS/openNDS/blob/99b95176cc26e49a4c092381fe1d04a3e2a1e27d/src/ndsctl.c#L255

Once set in config:
```

root@OpenWrt:~# /usr/lib/opennds/libopennds.sh get_option_from_config ndsctlsocket
ndsctl.sockroot@OpenWrt:~#
```

then ndsctl works as expected.

I am not sure if it is a documentation issue or a bug but the code seems fully correct:

https://github.com/openNDS/openNDS/blob/99b95176cc26e49a4c092381fe1d04a3e2a1e27d/src/ndsctl.h#L31

**Comment by bluewavenet** [comment]
@pierrejoye 
I cannot replicate this here.
Please show, in the non-working state, the output of:
`uci show opennds`

**Comment by pierrejoye** [comment]
With no entry set:

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].gatewayinterface='phy1-ap0'
opennds.@opennds[0].faskey='37564xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx74287'
```

And set:
```

opennds.@opennds[0]=opennds
opennds.@opennds[0].ndsctlsocket='ndsctl.sock'
opennds.@opennds[0].gatewayinterface='phy1-ap0'
opennds.@opennds[0].faskey='37564xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4287'
```

**Comment by bluewavenet** [comment]
@pierrejoye 

> Device: [OpenWrt 23.05.2 (r23630-842932a63d)](https://openwrt.org/)
> Opennds: opkg opennds - 10.2.0-1

and
`opennds.@opennds[0].gatewayinterface='phy1-ap0'`

`phy1-ap0` is a wireless interface name. 

OpenWrt 23.05.x requires wireless interfaces to be part of a bridge. If not, the result in indeterminate.
By default the bridge device is `br-lan` and this is also the default for openNDS.

OpenNDS requires `gatewayinterface` to be a bridge device.
With this config, I would expect openNDS to fail anyway.

Try:
```
uci delete opennds.@opennds[0].ndsctlsocket='ndsctl.sock'
uci delete opennds.@opennds[0].gatewayinterface='phy1-ap0'
uci delete opennds.@opennds[0].faskey='37564xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx4287'
uci commit opennds
service opennds restart

```

**Comment by pierrejoye** [comment]
it is working,  but I will modify accordingly (I changed as opennds was affecting other wifi when using br-lan), I am only testing for now.

However the issue is about ndsctl failing, I am completely not sure why as the code seems 100% correct.

**Comment by pierrejoye** [comment]
[log opennds.txt](https://github.com/openNDS/openNDS/files/14468578/log.opennds.txt)

Debugging further, I started from a fresh setup. br-guest and wifi work correctly (also the firewall to reject trafic to lan).

br-guest being the gatewayinterface:

```
opennds.@opennds[0]=opennds
opennds.@opennds[0].debuglevel='3'
opennds.@opennds[0].ndsctlsocket='ndsctl.sock'
opennds.@opennds[0].gatewayinterface='br-guest'
opennds.@opennds[0].faskey='xxx'
```

Now it fails to initialize the firewall (debug level 3 log attached):

```
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: nftables command [ add rule ip nds_filter ndsNET counter reject ], iteration [ 0 ]return code [ 0 ]
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: safe_snprintf: [ 46 ]
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: restart command [ /usr/lib/opennds/dnsconfig.sh "restart_only" & ]
Sat Mar  2 08:21:13 2024 daemon.info opennds[19933]: Dnsmasq restarted
Sat Mar  2 08:21:13 2024 daemon.err opennds[19933]: Error initializing firewall rules! Cleaning up
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: Destroying our nftables entries
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: Executing command: /usr/lib/opennds/libopennds.sh "delete_chains"
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: Reading command output
Sat Mar  2 08:21:13 2024 daemon.debug opennds[19933]: command output: []
Sat Mar  2 08:21:13 2024 daemon.info opennds[19933]: Chain delete request sent
Sat Mar  2 08:21:13 2024 daemon.err opennds[19933]: Exiting because of error initializing firewall rules
```

I realize that may not be the right place for that specific issue (should the openwrt forum be used in general? for this?), but trying to see why the ndsctl fails while opennds is running.

**Comment by bluewavenet** [comment]
@pierrejoye 

`Sat Mar  2 08:40:43 2024 daemon.debug opennds[22955]: nftables command [ add rule ip nds_filter ndsNET ip daddr status.client tcp dport 2050 counter accept ], iteration [ 0 ]return code [ 1 ]`

This is a known issue caused when dnsmasq takes a long time to come up. This depends on the speed of the hardware and the dnsmasq config (especially when there are multiple dhcp configs when dnsmasq can take multiple 10's of seconds to get started).

A proper fix for this is built in to the next version of openNDS where openNDS waits for dnsmasq.

There is a quick workaround involving an edit of an ash script (see later).

> trying to see why the ndsctl fails while opennds is running.

If openNDS is not running (or starts and aborts because of config problems or slow dnsmasq), then ndsctl will error if you try to use any of its options that require the openNDS socket.

_**The workaround for v2.2.0 is to patch the file /usr/lib/opennds/dnsconfig.sh as follows:**_

Line 60 reads:
`/etc/init.d/dnsmasq restart &`

Change it to:
`service dnsmasq restart ; sleep 20`

This will force dnsconfig.sh to wait until dnsmasq has restarted, rather than running the init.d restart in the background without waiting.

After editing, make sure the file is still executable.

Now restart openNDS:
`service opennds restart`

Does it work for you?

**Comment by pierrejoye** [comment]
> Does it work for you?

That made it :))

Thank you very much!

Also, I can't reproduce either the ndsctl issue I was reporting first. Whether I set it or not, it is working now. I am closing this issue :)
