### ISSUE TITLE
Feature Request - Perform dynamic updates with `ndsctl`

### ISSUE THREAD

**Issue by sicelo** [openNDS/openNDS#58]
1. I notice that when using `ndsctl` it is not possible to update client settings dynamically. E.g. for an Authenticated client, if you need to change its download rate or quota, you must first deauth it.
Would it be possible to allow rerunning the auth command with updated parameters without needing to deauth the client?

2. Perhaps when requested for information (using json, clients or status commands), `ndsctl` could also display the quotas that have been applied for a particular client. It seems to me that currently you cannot see what quotas are in effect for an already authenticated client

**Comment by bluewavenet** [comment]
@sicelo 

> allow rerunning the auth command with updated parameters

It is possible, maybe a new command rather than auth. I'm not convinced it is needed though. What is your use case?

> ndsctl could also display the quotas that have been applied for a particular client.

Yes, but your FAS already knows this information.... Again, explain your use case.

**Comment by sicelo** [comment]
For #2, I agree. I might just be looking for a lazy/convenience setting. But yes, the FAS could save this info itself

For #1, for example, let us say I have set a 100MB quota for a certain client, and it has already used 95MB. It will shortly be deauth'd. However, I might want to re-provision it with another quota allotment, but not have to deauth it first.

In other words, I'm using openNDS for a paid hotspot, where the clients pay every MB :)

**Comment by bluewavenet** [comment]
@sicelo

> ndsctl could also display the quotas that have been applied for a particular client 

Agreed, this could be a useful enhancement, I'll put it on the todo list. However pull requests are welcome (hint).

> I might want to re-provision it with another quota allotment

In my experience this is always best done as an automated process where the client depletes quota and is deauthed, then has to log in again, this time getting the revised quota. Otherwise someone has to be on duty 24/7 to manually update "stuff".
Re-provisioning should be a function of FAS, ensuring the client also gets a reminder of ToS and anything else FAS wants to say.

### Business Model
> clients pay for every MB

As a business model, at least in Europe, US, Canada etc paid venue wifi has become untenable or at best a very limited niche application. This is mainly due to:
 * the prevalence of mobile data where clients consider charges over what they have already paid (for their mobile data) are to be avoided even to the extent of not visiting the venue.
 * the main use of public wifi as a means of attracting customers to venues. eg coffee shop "A" charges for wifi and is empty, whilst coffee shop "B" is packed as they offer free wifi (possibly with advertising that could generate revenue for the venue).
 * Even when mobile data is not available in a location, people will actively search out venues with free wifi and generally "do without" if they cannot find free access.
 * Businesses still trying to charge are regarded as greedy and/or untrustworthy.

This change began, in the areas I mentioned, over 10 years ago. I don't know about your area but would expect the same to have already happened or be well into the process of happening.

The only viable exception is for a community mesh network (or similar), with a fully autonomous FAS being essential. However even in this use case, unlimited quota by subscription (with fair use policy perhaps) is more of the norm.

Your comments would be welcome.

**Comment by sicelo** [comment]
> As a business model, at least in Europe, US, Canada etc paid venue wifi has become untenable or at best a very limited niche application
> This change began, in the areas I mentioned, over 10 years ago. I don't know about your area but would expect the same to have already happened or be well into the process of happening

This is true. However, where I am (.SZ), even the most generous Free WiFi is typically capped at a max of 100MB. The majority of Free WiFi services are provided by municipalities/government (read, not working most of the time) or expensive restaurants/etc. In general, Internet costs quite a bit here, especially mobile data, so there aren't too many businesses/venues operating free WiFi yet.

As a result, there is still *some* business in running a cafe/hotspot. But but yeah, it won't be a high-revenue business eitherr

**Comment by bluewavenet** [comment]
@sicelo 
It was worth making sure you were aware of this - we still get unscrupulous companies trying to sell paid Internet solutions to venues with little or no technical knowledge. The venues suddenly find, after signing, up that people walk away and they are left with high subscription charges and no income from the wifi.

Given your situation then yes it would be worthwhile. If you want my free advice to help with your proprietary development  feel free to email me. Otherwise ask questions here.

**Comment by bluewavenet** [comment]
@sicelo 

> ndsctl could also display the quotas that have been applied for a particular client

I'm implementing this now.

**Comment by bluewavenet** [comment]
@sicelo 
While testing, if you want to see the quota processing in action, set debuglevel to 3 and run logread periodically.
ie
`ndsctl debuglevel 3`

Then periodically run:
`logread | grep opennds`

**Comment by bluewavenet** [comment]
@sicelo 
A typical log output (with rate quotas set as well) would be like:
```
Tue Sep 29 11:08:35 2020 daemon.info opennds[22207]: Client @ 10.13.1.138 74:de:2b:b1:70:33, quotas:
Tue Sep 29 11:08:35 2020 daemon.info opennds[22207]: 	Download DATA quota (kBytes): 200000, used: 6080
Tue Sep 29 11:08:35 2020 daemon.info opennds[22207]: 	Upload DATA quota (kBytes): 100000, used: 583
Tue Sep 29 11:08:35 2020 daemon.debug opennds[22207]: Window start [1601377585] - window counter [0]
Tue Sep 29 11:08:35 2020 daemon.debug opennds[22207]: in_window_start [5031011] - out_window_start [485368]
Tue Sep 29 11:08:35 2020 daemon.debug opennds[22207]: durationsecs [130] download_bytes [1049517] upload_bytes [98282]
Tue Sep 29 11:08:35 2020 daemon.info opennds[22207]: 	Download RATE quota (kbits/s): 100, Current average download rate (kbits/s): 64
Tue Sep 29 11:08:35 2020 daemon.info opennds[22207]: 	Upload RATE quota (kbits/s): 20, Current average upload rate (kbits/s): 6

```

**Comment by sicelo** [comment]
That's very nice!
But yes, in the meantime, it will definitely be easiest (and most sensible) to use the FAS for this.

**Comment by bluewavenet** [comment]
@sicelo 
Release 6.1.0 will have improved ndsctl reporting. Coming soon :-D

Work in progress - example:
```
==================
openNDS Status
====
Version: 6.1.0beta
Uptime: 4m 46s
Gateway Name: Test Captive Portal
Managed interface: br-lan
Managed IP range: 0.0.0.0/0
Server listening: http://10.13.1.1:2050
Binauth: Disabled
Preauth: Disabled
FAS: Secure Level 2, URL: http://10.13.1.1:8880/login.php
Client Check Interval: 60s
Preauth Idle Timeout: 30m
Auth Idle Timeout: 120m
Download rate limit (default per client): no limit
Upload rate limit (default per client): no limit
Download quota (default per client): 200000 kB
Upload quota (default per client): 100000 kB
Total download: 1753 kByte; avg: 49.04 kbit/s
Total upload: 187 kByte; avg: 5.25 kbit/s
====

```

**Comment by bluewavenet** [comment]
@sicelo 
I keep having to work on the day job, but getting there slowly on v6.1.0 ;-)

**Comment by sicelo** [comment]
Thanks :)

**Comment by bluewavenet** [comment]
@sicelo 
Time has flown by and v7.0.1 is now released. No progress on your Feature Request though - sorry.

**Comment by sicelo** [comment]
:-)
It's alright. So far openwrt's opennds 5.0.2 is able to do all I want
