### ISSUE TITLE
Inter-portal roaming

### ISSUE THREAD

**Issue by esfxra** [openNDS/openNDS#604]
Hello,

First, thanks for OpenNDS! I'm a big fan of it as a captive portal that can run on OpenWrt.

I have a question about achieving inter-portal roaming with OpenNDS. There are some hints in the documentation about using preemptive authentication and FAS, which suggest this could be accomplished with the Pre-emptive Clients list.

My goal is to have multiple routers in a neighborhood, and ensure that when a user moves from point A to point B, they remain authenticated without the captive portal reappearing, unless the session has expired due to quota limits or timeouts.

It seems possible to write these authenticated clients as part of the preemptive list. However, I would need to do this with a separate service on the router that is constantly syncing this list with the backend's auth list, correct?

Any pointers or ideas to a better approach are appreciated as well. Thanks again!

**Comment by bluewavenet** [comment]
@esfxra

> It seems possible to write these authenticated clients as part of the preemptive list. However, I would need to do this with a separate service on the router that is constantly syncing this list with the backend's auth list, correct?

Inter Portal roaming is not built in to any of the example FAS scripts but has certainly been done by some commercial users.

The fas-aes-https and fas-hid-https example scripts make use of the openNDS authmon daemon for FAS/opennds communications, so the basics are already supported.
See:
https://opennds.readthedocs.io/en/stable/fas.html#authentication-method-for-fas-secure-enabled-level-3-authmon-daemon

> when a user moves from point A to point B, they remain authenticated without the captive portal reappearing, 

This is problematic. The implementations I am aware of require initial "self account generation" by users with the account details and current status held and updated thereafter in the Internet hosted FAS server's database.

Due to the almost universal implementation of mac address randomisation, FAS account verification cannot be done by mac address. When a user moves to another location, their mac address will (usually) change, so pre-emptive authentication will not work properly as it is based on mac address.

**Comment by esfxra** [comment]
@bluewavenet 
> This is problematic. The implementations I am aware of require initial "self account generation" by users with the account details and current status held and updated thereafter in the Internet hosted FAS server's database.

Might not be too far on this end. I have a backend based on fas-aes-https with user registration, and with a status for each connection the user has. The connection flow is roughly the following:
- User signs up (or signs in)
- User requests to connect in the portal's UI
- Connection status is created on the DB as `pending`
- Status stays `pending` until the authmon loop acknowledges it
- Status changes to `connected`
- Status changes to `ended` with the help of binauth signals

> The fas-aes-https and fas-hid-https example scripts make use of the openNDS authmon daemon for FAS/opennds communications, so the basics are already supported.

The `auth_list` I return has multiple encoded strings like in the fas-aes-https example. Each of these strings is built with:
- the hash id
- session length
- upload rate
- download rate
- upload quota
- download quota
- custom params

Could I replace the hash id with the mac address of the client? Asking because it seems authmon.sh will accept it.

Of course assuming the user has turned off mac randomization since that is definitely a show stopper.

**Comment by bluewavenet** [comment]
@esfxra 

> Of course assuming the user has turned off mac randomization since that is definitely a show stopper.

Most people do not even know what it is, let alone switch it off.
But it is worse than that - most implementations only give you the option of switching it off _**after**_ connecting... Then it is only off for that ssid.

So really, it is a showstopper and not worth wasting time on.

But you do have user registration, so this will be/can be common for users as they move around locations.
