### ISSUE TITLE
Proxy / Tunnel

### ISSUE THREAD

**Issue by lexavey** [openNDS/openNDS#621]
How to use with proxy, I'm running proxy, while activate nds, traffict is not proxied by proxy software, its direct to wan interface, should be proxied first by defaut.

Edit: 
I always wonder openNDS work in my scenario, so I just keep try to install openNdS when I notice a update.
Previous issue is proxy not blocked by default https://github.com/openNDS/openNDS/issues/540

**Comment by bluewavenet** [comment]
@lexavey 
As I stated in your previous issue, _**the problem lies with openclash, not openNDS**_:

> If Openclash was not dependent on iptables and was an officially recognised OpenWrt package, it would be worth investing time into seeing what is wrong, but unfortunately this is not the case.

 * In its current form, openclash will never be accepted into official OpenWrt.
 * In its current form, openclash will never work with openNDS 
 

> I always wonder openNDS work in my scenario, so I just keep try to install openNdS when I notice a update.

The only way you will get openclash to work is to rewrite it yourself or get its developers to do it for you.
