### ISSUE TITLE
issue with compiling 

### ISSUE THREAD

**Issue by guest-88** [openNDS/openNDS#79]
Hi
I'm on kali linux running machine with the latest version. I've already successfully installed the required packages for Debian as it is written in the README.txt file:    
apt install build-essential debhelper devscripts
apt install libmicrohttpd-dev dh-systemd
however when I run the command : dpkg-buildpackage
I get this error : 
dpkg-source: error: source package name 'openNDS' is illegal: character 'N' not allowed
dpkg-buildpackage: error: dpkg-source --before-build . subprocess returned exit status 255

Would you help me to sort out this issue ? 
Thanks.

**Comment by bluewavenet** [comment]
@guest-88 
Thanks for pointing this out. The README.md file is very outdated and should have been rewritten quite some time ago, but I guess hardly anyone has tried to follow it, or at least no-one has reported before.

The Debian repository for libmicrohttpd.dev is very old, and incompatible with openNDS. openNDS uses the "new" MHD API.

You can find full compile/install instructions here:
https://opennds.readthedocs.io/en/stable/compile.html#linux-unix-compile-in-place-on-target-hardware

**Comment by skra72** [comment]
The error

dpkg-source: error: source package name 'openNDS' is illegal: character 'N' not allowed

can be resolved by making the package name in the linux_debian/changelog all lower case. Once 'openNDS' has been changed to 'opennds' the Debian package build works again.

**Comment by bluewavenet** [comment]
@skra72 Thank you.
Yes this was mentioned elsewhere. **Is it worth the effort building a package though?**
In addition, you currently have to compile the up to date version of libmicrohttpd-nossl for Debian as well, for compatibility reasons.

**Comment by skra72** [comment]
Having a Debian package is helpful when deploying to systems with low space available like Raspberry Pi's with not enough space for build tools. 

The microhttpd version is an issue, indeed. However, besides (critical?) bug fixes the breaking API changes are mainly about changing the return type from int to enum of certain function types. So on binary level this is still compatible. Only the compilers gives type errors because of the changes return type.

I only had a brief look at the sources, but wouldn't it work to add a compiler switch that defines the libmicrohttpd_cb function depending on MHD_VERSION of microhttpd.h? That could make everything easily compilable even on Debian systems with older libmicrohttpd-dev installations. 

Cheers!

**Comment by bluewavenet** [comment]
@skra72 

> Having a Debian package is helpful when deploying to systems

True

> systems with low space available like Raspberry Pi's with not enough space for build tools.

All Rpi models, even the Zero, have more than enough resources for compiling in place so this is not an issue in itself. Perhaps if installing or upgrading in "fully loaded" live systems there might be an issue. But then a quick SD card swap might be the best way of minimising downtime.
In addition, due to its hardware ie lack of router grade network interfaces, Rpi does not make a good router. Rolling out openNDS on a separate dedicated router grade hardware makes much more sense in a production environment. (I have done just this, with an OpenWrt mini-router powered from the Pi usb and connected "pi to router" by ethernet - resulting in a very cost effective and reliable solution)

> The microhttpd version is an issue

The Debian package repository holds an outdated version that has "critical" issues, if not bugs. If used, form data can be altered in a non standard way (urlencoding). In openNDS, this problem makes username/password login unreliable/unusable, for example. The MHD API change came at more or less the same time as the fix for this issue.

As openNDS **requires** to be run on a router configured device, the use of openNDS under OpenWrt is by far the most common, being packaged for thousands of hardware targets, including RPi. This is the reasoning that the effort has not been put into packaging for Debian or other operating systems.

This is not saying packages for other operating systems are not useful, but compiling in place works well enough in most cases where a specific OS is mandated. Indeed, I have personal experience of this with OpenSuse OS on corporate supported server hardware.

> wouldn't it work to add a compiler switch that defines the libmicrohttpd_cb function depending on MHD_VERSION of microhttpd.h?

Yes, I am sure there is a way of doing it. **_Feel free to submit a PR_**. But you must make sure it has no effect on cross compiling for OpenWrt targets.
