### ISSUE TITLE
Display custom page and access openNDS variables in gateway url root

### ISSUE THREAD

**Issue by ClydeAmazing** [openNDS/openNDS#82]
Hello openNDS Team,

Is there any way I could display a custom webpage and subsequently get/use existing openNDS variables in gateway root url when client is already authenticated? (http://[gateway_ip]:2050/) This is very useful when client just want to know the status of its current connection to NDS.

Useful variables on custom page:
$clientip
$clientmac
$clientupload
$clientdownload
$uptime
$status (maybe, i guess this is only available in status redirect url.)
etc.

Currently, (as far as I know) those variables are only available on initial client capture via splash.html (client status is preauthenticated) and in status.html which is only triggered when the user accesses http://[gateway_ip]:2050/[authdir] and is already authenticated. Accessing status page manually does not return the variables.

Please let me know if this is possible.
Thank you.

**Comment by bluewavenet** [comment]
@ClydeAmazing 
Please state your current versions of both openNDS and operating system (including the OS type).

Do you mean you want an enhanced client status page that clients (not administrators) access?
For the purposes of better understanding of your issue, it would be useful to know more about the application you have in mind for this.

_For a client accessible status page, the short answer is probably yes - depending on lots of things._

**Note:** Legacy splash html pages are deprecated and disabled by default from openNDS version 7.0.0 onwards.
They are replaced by a default PreAuth FAS script that dynamically generates html in response to client requests.
The current version of openNDS is 7.0.1 and release 7.1.0 is coming soon.

> Accessing status page manually does not return the variables

This is because the legacy status page is a static html template. This means the page is "dumb" and must be called by openNDS for serving to the client and not requested by the client itself.

Consider also that unless a client is authenticated, many of the client status "variables" will not be set, so getting a preauthenticated client status is of little value.

**Comment by ClydeAmazing** [comment]
@bluewavenet 
Thank you for your prompt response.

> Please state your current versions of both openNDS and operating system (including the OS type).

I'm using openNDS v6.0.0 on OpenWRT running on Orange PI R1 SBC

> Do you mean you want an enhanced client status page that clients (not administrators) access?

Yes.  The thing that I really want to achieve is to have a "status page" that can be accessed manually by the client anytime while the client is authenticated prefererably under the root url (http://[gateway_ip]:2050/). This page should have access to some openNDS "variables" at least the client MAC Address ($clientmac).

>For the purposes of better understanding of your issue, it would be useful to know more about the application you have in mind for this.

What I have in mind is to display custom user information coming from an external API, each API request is identified using the client's MAC address. 
I initially planned to host the status page externally via external FAS but I had a hard time figuring out how to identify clients when they manually visit the page. (It is not a problem identifying client in initial authentication since user information (such as MAC address) can be supplied in the request url. Subsequent request to that particular page is where I have a bit of a problem)

The exposed $clientmac variable in the "status page" will be used in the external API request/s.

>Note: Legacy splash html pages are deprecated and disabled by default from openNDS version 7.0.0 onwards.
They are replaced by a default PreAuth FAS script that dynamically generates html in response to client requests.
The current version of openNDS is 7.0.1 and release 7.1.0 is coming soon.

I'll take note on this one and probably will start to fiddle with PreAuth FAS Script. I just read the latest documentation for PreAuth FAS script and it has a lot of potential to solve most of my problem.

>This is because the legacy status page is a static html template. This means the page is "dumb" and must be called by openNDS for serving to the client and not requested by the client itself.

This is also what I initially thought.

**Comment by bluewavenet** [comment]
@ClydeAmazing 

> a "status page" ... accessed manually by the [authenticated] client ..[at].. url (http://[gateway_ip]:2050/)

The problem here is identifying the client. Normally the client CPD triggers openNDS so client identification is automatic.
Manual identification is possible though. To achieve this openNDS will have to read the request headers to get the client ip address.
This looks like it would be a useful enhancement and fairly easy to implement. I will have a look and see if we can get it into the next release.
Currently (in v7.0.1 at least) openNDS serves its Error 404 page when accessing  http://[gateway_ip]:2050, so adding a custom "user-status" section to login.sh should be straightforward......

> I'll take note ... and probably will start to fiddle with PreAuth FAS Script.

Yes, but be aware that there are numerous config and cosmetic changes to PreAuth in the upcoming release although the basic operation is the same. Best for now to restrict yourself to fiddling rather than developing ;-)

**Comment by ClydeAmazing** [comment]
@bluewavenet 

>This looks like it would be a useful enhancement and fairly easy to implement. I will have a look and see if we can get it into the next release.

Thank you for taking a look on this one and for considering this as a feature on your next releases. I'll look forward to that 👍 

>Yes, but be aware that there are numerous config and cosmetic changes to PreAuth in the upcoming release although the basic operation is the same. Best for now to restrict yourself to fiddling rather than developing ;-)

This is duly noted :D

**Comment by bluewavenet** [comment]
@ClydeAmazing 
I have now implemented a Client Status Page accessed by a configurable gateway FQDN (eg accessed at http://status.client) or if not configured, by http://[gatewayip]:[gatewayport]

Client status page has a refresh button to update the status and a logout button.
The information displayed is similar to the output of ndsctl json [client_ip].

The status page can be customised by editing a script file.

When the logout button is clicked, a http status code 511 "Network Authentication Required" page is displayed with a login button (RFC 6585).

This will be included in the next release.

**Comment by ClydeAmazing** [comment]
@bluewavenet 
Wow! This is so cool. Can't wait to try.
Thanks!

**Comment by bluewavenet** [comment]
@ClydeAmazing 
Version 8.0.0 is now released. A pull request has been opened at OpenWrt for inclusion there.
See:
https://opennds.readthedocs.io/en/stable/clientstatus.html

**Comment by ClydeAmazing** [comment]
@bluewavenet 
Thank you for this new year present.
Will try this one out, been waiting for this for a long time now.. :D
