### ISSUE TITLE
Session Length not working

### ISSUE THREAD

**Issue by aelitasch** [openNDS/openNDS#85]
Does anyone know why session_length is not working?

https://i.imgur.com/3pKbpat.jpg
https://i.imgur.com/Bqg7NrW.jpg

if u see at the picture above, i already set session_length to 180 but when i look at ndsctl printout, session end in 20 hours

**Comment by sicelo** [comment]
`ndsctl status` shows a session length of 1200 (20 hours). In your userlist.dat you are applying session_length of 1200 to user `member`. Therefore, it means that the client you are seeing in `ndsctl` used the credentials for `member`.

IOW, it's all working as expected

**Comment by aelitasch** [comment]
> `ndsctl status` shows a session length of 1200 (20 hours). In your userlist.dat you are applying session_length of 1200 to user `member`. Therefore, it means that the client you are seeing in `ndsctl` used the credentials for `member`.
> 
> IOW, it's all working as expected

Okay i already delete all except username with "kenny" and i set the session_length to 180 and the session still end in 20 hours. 
![570778](https://user-images.githubusercontent.com/75564486/101613371-41b9a180-3a3e-11eb-8120-e78add899ea4.jpg)

**Comment by sicelo** [comment]
1. What is the default session length defined in `/etc/config/opennds`?

2. The clients we see in the picture used the `kenny` credentials?

**Comment by aelitasch** [comment]
> 1. What is the default session length defined in `/etc/config/opennds`?
> 2. The clients we see in the picture used the `kenny` credentials?

ok, the default session timeout in opennds config is 1200 (now i understand why it always 20h) but how can i create 1 account for 1 session timeout? ex: create username kenny with session_length=180 and username guest with session_length=3600?

**Comment by sicelo** [comment]
@bluewavenet will help you better since I have no experience with userlist (I use FAS for my setup).

What I would do is copy the string that gets echoed out in line 133 of `binauth_sitewide` and temporarily log it out around line 150/151, then see what ends up in `/tmp/ndslog/binauthlog.log`. As far as I can tell from your description, NDS does not receive the session lengths you're attempting to set, hence the default in config/opennds gets used.

**Comment by sicelo** [comment]
It might also be interesting to show us your actual `/etc/config/opennds` file.

**Comment by bluewavenet** [comment]
@aelitasch 
That seems to be a bug. I'll look into it.

What versions of operating system and openNDS are you using, and what hardware?

**Comment by aelitasch** [comment]
> @aelitasch
> That seems to be a bug. I'll look into it.
> 
> What versions of operating system and openNDS are you using, and what hardware?


I'm using windows 10, opennds ver : 7.01
here's the screenshot for /etc/config/opennds file
![Screenshot (80)](https://user-images.githubusercontent.com/75564486/101859920-35008f00-3b9f-11eb-98e2-a7d8d7ae3378.png)

**Comment by aelitasch** [comment]
> @bluewavenet will help you better since I have no experience with userlist (I use FAS for my setup).
> 
> What I would do in the meantime is to copy the string that gets echoed out in line 133 of `binauth_sitewide` and temporarily log it out around line 150/151, then see what ends up in `/tmp/ndslog/binauthlog.log`. As far as I can tell from your description, NDS does not receive the session lengths you're attempting to set, hence the default in config/opennds gets used.

like this?
![Screenshot (83)](https://user-images.githubusercontent.com/75564486/101861321-56af4580-3ba2-11eb-8754-afda3eef08ab.png)

here's the log file
[binauthlog.log](https://github.com/openNDS/openNDS/files/5677029/binauthlog.log)

**Comment by aelitasch** [comment]
@bluewavenet umm is this the bug? i think it should be while read userlist right? or am i wrong? 
![Screenshot (84)](https://user-images.githubusercontent.com/75564486/101861769-75faa280-3ba3-11eb-8ed9-7011505c16b2.png)

**Comment by sicelo** [comment]
All looks okay. 
As @bluewavenet mentioned, there's clearly a bug here, and I think it's in openNDS 7.x.

If I'm not mistaken, your config would work fine in openNDS 5.x (which I use), as clearly NDS is passed the correct info

**Comment by aelitasch** [comment]
> All looks okay to my untrained eye.
> 
> As @bluewavenet mentioned, there's clearly a bug here, and I think it's in openNDS 7.x.
> 

> If I'm not mistaken, your config would work fine in openNDS 5.x (which I use), as clearly NDS is passed the correct parameters.

ok my bad, im on opennds ver 5.20 not 7.01, i thought when i install opennds using opkg it will install the latest opennds (7x), so the bug is on opennds 5.20 and my openwrt ver is 19.07

**Comment by bluewavenet** [comment]
@aelitasch 
Screenshots can be useful, but generally it is better to cut and paste text into here where it can be marked as a "Quote" or "Code" block using the menu options at the top right of the text box.

This issue is now identified as a bug and is fixed. It was in one of the C code source files. Thank you for finding it :-D

**Note**: splash.html, splash_sitewide.html etc
These are legacy templated splash pages and their use is deprecated.

Templated splash pages are disabled by default in v7.x.x and will be removed entirely in later versions. These static html files are replaced by dynamic html generated using script files.

From the next release, the splash_sitewide.html, userlist.dat and binauth_sitewide.sh files will not even be installed.

This does not effect the use of BinAuth for post authentication processing such as setting quotas etc.

**Comment by bluewavenet** [comment]
@aelitasch 

> i thought when i install opennds using opkg it will install the latest opennds (7x),  ..... my openwrt ver is 19.07

openNDS v6.x.x onwards is not compatible with OpenWrt 19.07.x or earlier due to library api changes elsewhere.

openNDS 7.x.x or higher is available for OpenWrt Snapshot and will be included in the upcoming OpenWrt 2x.x.x release

It is possible to backport a patched version of 7.x.x to OpenWrt 19.07.x and this might be done after the next openNDS release.

**Comment by aelitasch** [comment]
> @aelitasch
> Screenshots can be useful, but generally it is better to cut and paste text into here where it can be marked as a "Quote" or "Code" block using the menu options at the top right of the text box.
> 
> This issue is now identified as a bug and is fixed. It was in one of the C code source files. Thank you for finding it :-D
> 
> **Note**: splash.html, splash_sitewide.html etc
> These are legacy templated splash pages and their use is deprecated.
> 
> Templated splash pages are disabled by default in v7.x.x and will be removed entirely in later versions. These static html files are replaced by dynamic html generated using script files.
> 
> From the next release, the splash_sitewide.html, userlist.dat and binauth_sitewide.sh files will not even be installed.
> 
> This does not effect the use of BinAuth for post authentication processing such as setting quotas etc.

@bluewavenet Thank you for confirming that it is a bug and you mention that you are going to remove the userlist.dat, can we still use custom username and password for login on the next update?

**Comment by bluewavenet** [comment]
@aelitasch 
In the new versions it is simple to modify the default login script to verify client credentials against your own database if required.

**Comment by aelitasch** [comment]
> @aelitasch
> In the new versions it is simple to modify the default login script to verify client credentials against your own database if required.

@bluewavenet one more question please
Will there be any instructions or documentation about how to backport the next opennds update to openwrt 19.07?
because right now i tried to install opennds 7.01 on my router but it always failed because the requirement for libmicrohttpd version is 0.9.71, and the problem is i cant install the latest libmicrohttpd.

**Comment by bluewavenet** [comment]
@aelitasch 
Backporting will be done by the openNDS project.

You can download both openNDS and libmicrohttpd-no-ssl from OpenWrt Snapshot, **copy to your router's /tmp directory** and then upgrade to the new version of **libmicrohttpd-no-ssl first**, followed by the new version of openNDS.

Use:
`opkg install /tmp/[package-file-name]`

**Comment by sicelo** [comment]
> This issue is now identified as a bug and is fixed. It was in one of the C code source files. Thank you for finding it :-D

Great work! Could you share the bug/fix here, so we could possibly recompile opennds 5.x with it?

**Comment by aelitasch** [comment]
> @aelitasch
> Backporting will be done by the openNDS project.
> 
> You can download both openNDS and libmicrohttpd-no-ssl from OpenWrt Snapshot, **copy to your router's /tmp directory** and then upgrade to the new version of **libmicrohttpd-no-ssl first**, followed by the new version of openNDS.
> 
> Use:
> `opkg install /tmp/[package-file-name]`

ok thank you, now i can install opennds 7 but the binauth also got an error :( i cant use binauth on opennds 7, i agree with @sicelo , could you share the bug fix for opennds 5 pls? :D

**Comment by bluewavenet** [comment]
@aelitasch @sicelo 
I will try to push a new beta with the bugfix to github later today or tomorrow if you want to compile yourselves. I think though the new release will only be a few days.

@aelitasch 

>  I .. install opennds 7 but the binauth also got an error 

I am running 7.0.1 here on 19.07.3 and not getting an error with BinAuth (the bug is there though - but no error)
If you mean session length is not working then this is expected. If you are getting an error though, please share it.

**Comment by aelitasch** [comment]
> @aelitasch @sicelo
> I will try to push a new beta with the bugfix to github later today or tomorrow if you want to compile yourselves. I think though the new release will only be a few days.
> 
> @aelitasch
> 
> > I .. install opennds 7 but the binauth also got an error
> 
> I am running 7.0.1 here on 19.07.3 and not getting an error with BinAuth (the bug is there though - but no error)
> If you mean session length is not working then this is expected. If you are getting an error though, please share it.

nevermind, my fault, there's no error, and btw have you upload the opennds 5 bug fix?

**Comment by bluewavenet** [comment]
@aelitasch 

> have you upload the opennds 5 bug fix?

No.
I found a few other issues with the beta then had to work at the day job ;)

**Comment by bluewavenet** [comment]
@aelitasch  @sicelo 
Well this issue is fixed and tested and merged into .... Version 8.0.0 :-D
Once I got started I could not stop ;-)
There are some major changes - hence the major version jump.
This will be released "imminently" after a final check of the documentation, and then pushed to OpenWrt over the next few days.

**Comment by bluewavenet** [comment]
@aelitasch @sicelo
v8.0.0 is released and a PR has been opened at OpenWrt
