### ISSUE TITLE
How do i change the gatewayaddress?

### ISSUE THREAD

**Issue by andy-yeung** [openNDS/openNDS#97]
if I want to change the GatewayAddress(172.131.10.94) to 192.168.50.1, how do I add/edit it in opennds.conf?
![image](https://user-images.githubusercontent.com/62322681/104984160-2c766080-5a49-11eb-96bc-21ced5e297e5.png)

**Comment by andy-yeung** [comment]
![image](https://user-images.githubusercontent.com/62322681/104986684-83326900-5a4e-11eb-840d-c967d913e4a1.png)
And how do I fix line91 in login.sh?

**Comment by bluewavenet** [comment]
@andy-yeung 

> if I want to change the GatewayAddress(172.131.10.94) to 192.168.50.1, how do I add/edit it in opennds.conf?

This is set by your network configuration (for wlan0 in this case) - as I think you have found out.

>  And how do I fix line91 in login.sh?

How is this related to gatewayaddress?
Please open a new issue, stating the version of the operating system you are using on your pi and what consequences, if any, there are due to this warning.
