### ISSUE TITLE
Cant access internet after the Authentication

### ISSUE THREAD

**Issue by andy-yeung** [openNDS/openNDS#98]
**The version of the operating system:**
Raspbian

**Consequences:**
![IMG-6782](https://user-images.githubusercontent.com/62322681/105124830-eb984d80-5b15-11eb-8596-a0accbeb616c.PNG)

I had changed the GatewayAddress to 192.168.50.1 and Interface to uap0.
but still have no idea about having no internet connection.
supposed that there would be a wifi logo instead of "LTE" on the top right side of the screen picture after the authentication.

Checked the ip:
![image](https://user-images.githubusercontent.com/62322681/105124621-77f64080-5b15-11eb-86c2-a313eb3ef494.png)

**Comment by sicelo** [comment]
Hi. Can your iPhone access internet from the Raspberry Pi if you stop openNDS?

**Comment by andy-yeung** [comment]
> Hi. Can your iPhone access internet from the Raspberry Pi if you stop openNDS?

No. so I don't know which part is setting wrong..

**Comment by bluewavenet** [comment]
@andy-yeung 
As clients cannot get to the Internet even with openNDS not running, then the problem lies with your network configuration.

Before running openNDS, your router must comply with some basic prerequisites. See the documentation:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

There are many web pages that can help you setting up. This one gives a good list of the steps:
https://opennds.readthedocs.io/en/stable/install.html#prerequisites

Disable openNDS first, before working on your network configuration.
Once clients can connect and use the Internet, that is the time to re-enable and start openNDS.

Stop:
`sudo systemctl stop openNDS`

Disable:
`sudo systemctl disable openNDS`

Enable:
`sudo systemctl enable openNDS`

Start:
`sudo systemctl start openNDS`

**Note**: "Raspbian" is the name if the Linux distribution. Its official name is Raspberry Pi OS

**What is the version you are using?** I would recommend Raspios Lite
The current version is https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-lite.zip

**Which model Rpi are you using?**

**Comment by andy-yeung** [comment]
> @andy-yeung
> As clients cannot get to the Internet even with openNDS not running, then the problem lies with your network configuration.
> 
> Before running openNDS, your router must comply with some basic prerequisites. See the documentation:
> https://opennds.readthedocs.io/en/stable/install.html#prerequisites
> 
> There are many web pages that can help you setting up. This one gives a good list of the steps (edit - posted wrong link):
> https://gridscale.io/en/community/tutorials/debian-router-gateway/
> 
> Disable openNDS first, before working on your network configuration.
> Once clients can connect and use the Internet, that is the time to re-enable and start openNDS.
> 
> Stop:
> `sudo systemctl stop openNDS`
> 
> Disable:
> `sudo systemctl disable openNDS`
> 
> Enable:
> `sudo systemctl enable openNDS`
> 
> Start:
> `sudo systemctl start openNDS`
> 
> **Note**: "Raspbian" is the name if the Linux distribution. Its official name is Raspberry Pi OS
> 
> **What is the version you are using?** I would recommend Raspios Lite
> The current version is https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-lite.zip
> 
> **Which model Rpi are you using?**

Thank you for your replying!!
I'm using Raspberry Pi 3B and I solved the connection problem! :-D
but I can't arrive at my local file, let say: I want to arrive at 192.168.50.1/test.txt but Error 404 - Not Found.
is it related to port or the document root in 000-default.conf?

**Comment by andy-yeung** [comment]
should I change the WebRoot to /var/www in opennds.conf?

**Comment by bluewavenet** [comment]
@andy-yeung 

>  I'm using Raspberry Pi 3B and I solved the connection problem! :-D

Can you confirm:
 * With openNDS stopped and disabled, a connecting client can now access the Internet
 * With openNDS enabled and started, clients are redirected to the default login page and can authenticate and get Internet access.

**If this is confirmed, can you please open a new issue for help with customisation.**

You should read the customisation section of the documentation:
https://opennds.readthedocs.io/en/stable/customize.html#customising-opennds

**Comment by bluewavenet** [comment]
@andy-yeung 

>  what's the difference between /resources/opennds.conf and /etc/opennds/opennds.conf?

/resources/opennds.conf is the generic Linux configuration file as found in the source files

/etc/opennds/opennds.conf is the generic Linux configuration file copied from the source files by `make install`
